{
 "title": "English Light",
 "time": { "from": "now-384d", "to": "now+14d" },
 "templating": {
  "list": [
   { "name": "lang", "query": "HU,RO,EN" },
   { "name": "theme", "query": "light,light" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "content": "<a target=\"_blank\" href=\"https://econ.ubbcluj.ro/\"><img id=\"flogo\" class=\"flogo\" alt=\"Babeș-Bolyai University\" src=\"//covid-large-html.csaladen.es/img/fsega_en.png\" style=\"height:80px!important;width:330px!important;\"/></a>"
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 1, "x": 7, "y": 0 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 0 },
   "content": "<div style=\"text-align:left;\"><h1>COVID-19 – Romanian Economic Impact Monitor</h1><h3> Impact of the coronavirus pandemic on the Romanian economy: facts and forecasts</h3></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "content": "<br><div class=\"lang\" style=\"text-align: center; font-size:16px;\">&nbsp;&nbsp;<a target=\"_self\" title=\"Română\" href=\"/d/ro\">RO</a>&nbsp;&nbsp;<a target=\"_self\" title=\"Magyar\" href=\"/d/hu\">HU</a>&nbsp;&nbsp;<a target=\"_self\" title=\"English\" href=\"/d/en\">EN</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"fa fa-paint-brush\"></i>&nbsp;&nbsp;<a target=\"_self\" title=\"Dark theme\" href=\"/d/en\"><i class=\"fa fa-circle\"></i></a>&nbsp;&nbsp;<a target=\"_self\" title=\"Light theme\" href=\"/d/en-light?theme=light\"><i class=\"fa fa-circle-o\"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style=\"font-size:20px;\" target=\"_blank\" title=\"Facebook\" href=\"https://www.facebook.com/covid19.roeim\"><i class=\"fa fa-facebook\"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style=\"font-size:20px;\" target=\"_blank\" title=\"Help\" href=\"https://github.com/denesdata/covid19-romania/wiki\"><i class=\"fa fa-question\"></i></a></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    },
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 5 },
   "content": "<p><span style=\"font-size:18px;\"><span style=\"font-size:26px;color:#c2a30a;\"><b>433</b></span> days passed since the first coronavirus case in Romania and currently there are <span style=\"font-size:26px;color:#d45f00;\"><b>27&nbsp;265</b></span> active cases.</span></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Infection rates by settlement 📆 3 May 2021",
   "type": "innius-video-panel",
   "description": "🕑 Updated at 10:34 on 3 May 2021  \n  \nInfection incidence rates (new case total of last 14 days/1000 people - with 17 to 3 days before the date displayed) per settlement (territorial administrative unit UAT)  \n  \n📊 [data.gov.ro](https://data.gov.ro/dataset/transparenta-covid)   ",
   "gridPos": { "h": 13, "w": 1, "x": 7, "y": 5 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Total cases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recoveries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "heals" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total immunized",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "total_immunized" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"base\".\"vaccine1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'total_immunized' OR \"type\" = 'total_first')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "content": "A research project carried out by researchers of the Faculty of Economics and Business Administration of the Babeș-Bolyai University (Cluj-Napoca, Romania), which includes the daily publication of data on the economic impact of the coronavirus pandemic in Romania. Interactive infographics refreshed on a daily basis are meant to offer a comprehensive and relevant picture about the current state of the Romanian economy.\nThe purpose of our website is to offer support for economic and policy decision makers in Romania by providing a precise and regularly updated analysis of the current situation caused by COVID-19, and by offering background studies for the development of forecasting scenarios with the aim to better protect society, employees, companies and supply chains",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Annual GDP forecast (2021)",
   "type": "singlestat",
   "description": "Annual forecast. Base scenario.  \n📊 Own calculation",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "gdp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quarterly GDP forecast (2021 Q1 vs. 2020 Q4)",
   "type": "singlestat",
   "description": "Quarterly forecast. Base scenario.  \n📊 Own calculation",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "gdpq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Depreciation of Romanian leu to the euro",
   "type": "singlestat",
   "description": "Depreciation of the Romanian leu to the euro since the first reported Covid-19 case in Romania (📅 26th of February).  \n📊 Own calculation based on data from [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "xch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Change of BET index",
   "type": "singlestat",
   "description": "Change of BET index since the first reported Covid-19 case in Romania (📅 26th of February).  \n📊 Own calculation based on data from [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "bet" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Annual budget deficit forecast (2021)",
   "type": "singlestat",
   "description": "  \n📊 [Romanian Fiscal Council](http://www.consiliulfiscal.ro/Opinie%20CF%20buget%202021%20si%20SFB.pdf)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "status_plot14" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Change in no of employees",
   "type": "singlestat",
   "description": "Seasonally adjusted (2019 average = 100)  \n📊 [INS](https://insse.ro/cms/ro)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "employees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unemployment",
   "type": "singlestat",
   "description": "  \n📊 [INS](https://insse.ro/cms/ro)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "unemployment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Google mobility index",
   "type": "singlestat",
   "description": "Composite index based on Google's mobility data. Is shows the average change in mobility of the population, compared to the average between 📅 15th of February - 1st of March.  Residential values inverted.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "mobility_mini" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "content": "<div style=\"text-align:right;\"><i class=\"fa fa-clock-o\"></i>&nbsp;The data is updated daily at <b>2:00PM</b>. Last updated on: <b>2021-05-03</b></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  { "title": "Status report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Incidence rates by settlement 📆 3 May 2021",
   "type": "innius-video-panel",
   "description": "🕑 Updated at 10:34 on 3 May 2021  \n  \nInfection incidence rates (new case total of last 14 days/1000 people - with 17 to 3 days before the date displayed) per settlement (territorial administrative unit UAT)  \n  \n📊 [data.gov.ro](https://data.gov.ro/dataset/transparenta-covid)   ",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "First vaccine doses administered (+) and people immunized (-)",
   "type": "graph",
   "description": "First vaccine doses administered by vaccine type (positive axis) and people immunized by vaccine type (negative axis)  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vaccine1",
     "query": "SELECT mean(\"value\") FROM \"base\".\"vaccine1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'total_administered' OR \"type\" = 'total_administered_astra_zeneca' OR \"type\" = 'total_administered_pfizer' OR \"type\" = 'total_administered_moderna')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered" },
      {
       "condition": "AND",
       "key": "type",
       "operator": "!=",
       "value": "total_administered_astra_zeneca"
      },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered_moderna" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered_pfizer" }
     ]
    }
   ]
  },
  {
   "title": "Short-term forecast of daily new coronavirus cases",
   "type": "graph",
   "description": "  \n📊 Own estimation, refreshes weekly",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    }
   ]
  },
  {
   "title": "Evolution of infection rates per county (new case total of last 14 days/1000 people)",
   "type": "heatmap",
   "description": "Evolution of infection rates per county (new case total of last 14 days/1000 people)  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/), Own estimation",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "county" ], "type": "tag" }
     ],
     "measurement": "counties3",
     "select": [
      [
       { "params": [ "case_14_cap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
     ]
    }
   ]
  },
  {
   "title": "Evolution of cases, recoveries and deaths in total",
   "type": "graph",
   "description": "All data is from the official government sources. Active cases is a calculated metric. <b>Active cases (own estimation)</b> is the cumulative total of the new cases from the last 14 days. <b>Active cases (official)</b> is the sum of Deaths and Recoveries substracted from the Total Cases.  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/)",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance1",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
     ]
    }
   ]
  },
  {
   "title": "Evolution of cases, recoveries and deaths per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "case/test" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "death_rate" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "case/test" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "death_rate" }
     ]
    }
   ]
  },
  {
   "title": "Positive test ratio and mortality rate",
   "type": "graph",
   "description": "The positive test ratio is the number of daily new cases divided by the number of daily tests. The mortality rate is the number of daily new deaths divided by the number of daily new cases.  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/), [Johns Hopkins University - CSSE](https://coronavirus.jhu.edu/data/mortality)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"base\".\"governance2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'case/test' OR \"type\" = 'death_rate')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case/test" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "death_rate" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT moving_average(mean(\"value\"), 14) FROM \"base\".\"governance2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'death_rate' OR \"type\" = 'case/test')) AND $timeFilter GROUP BY time(1d), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "death_rate" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "case/test" }
     ]
    }
   ]
  },
  {
   "title": "News",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 },
     "content": "<p><h2><i class=\"fa fa-newspaper-o\"></i>&nbsp;&nbsp;News</h2><div>Updates from the project team, mentions in the mass media and official government news and announcements</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Our Facebook posts",
     "type": "innius-video-panel",
     "description": "  \n📊 [COVID-19 Romanian Economic Impact Monitor Official Facebook Page](https://www.facebook.com/covid19.roeim)",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 51 },
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "counties2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Mass media presence",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 51 },
     "targets": [
      {
       "measurement": "global2",
       "query": "SELECT  \"media\", \"desc\", \"lang\",\"type\", \"link\" FROM \"base\".\"news1\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Global events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
     "content": "<p><h2><i class=\"fa fa-globe\"></i>&nbsp;&nbsp;Global events</h2><div>The most important global economic and social events and measures </div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evolution of active cases around the world",
     "type": "graph",
     "description": "❗ 📈 logarithmic scale  \n📊 [Johns Hopkins University - CSSE](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "global3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      },
      {
       "alias": "Romania (official)",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "active" }
       ]
      },
      {
       "alias": "Romania (own estimation)",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
       ]
      }
     ]
    },
    {
     "title": "Global events",
     "type": "table-old",
     "description": "The most important global economic and social events and measures   \n📊 [Reuters](https://www.reuters.com/), [Bloomberg](https://bloomberg.com/), [BBC](https://news.bbc.co.uk/), [WHO](https://www.who.int/), [ECB](https://www.ecb.europa.eu/), [IMF](https://www.imf.org/external/index.htm), [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "measurement": "global2",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Governmental measures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
     "content": "<p><h2><i class=\"fa fa-gavel\"></i>&nbsp;&nbsp;Governmental measures</h2><div>Summary of governmental social and economic measures</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Stringency of government measures in Romania and other countries",
     "type": "graph",
     "description": "Stringency is a relative indicator between 0 (mild) - 100 (severe).  \n📊 [University of Oxford - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langcountry",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langcountry" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "severity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "lang2", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "stringency" }
       ]
      }
     ]
    },
    {
     "title": "Population response to government stringency",
     "type": "innius-video-panel",
     "description": "Stringency is a relative indicator between 0 (mild) - 100 (severe).  \n📊 [University of Oxford - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 53 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "The decrease in mobility and the evolution of government severity, next to daily new cases",
     "type": "graph",
     "description": "Mobility and stringency are relative indicators between 0-100. Mobility values are reversed.  \n📊 [University of Oxford - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "severity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "lang2", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "country", "operator": "=", "value": "ro" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "stringency" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
       ]
      },
      {
       "alias": "Decrease in mobility",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance3",
       "select": [
        [
         { "params": [ "mobility_mini" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Economic measures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "List of economic measures",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 64 },
     "targets": [
      {
       "measurement": "social1",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social1\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "desc2" ], "type": "field" }
        ],
        [
         { "params": [ "desc3" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Social measures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "List of social measures",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 71 },
     "targets": [
      {
       "measurement": "social2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social2\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Financial measures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "List of financial measures",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 78 },
     "targets": [
      {
       "measurement": "global2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Macroeconomic indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 },
     "content": "<p><h2><i class=\"fa fa-forward\"></i>&nbsp;&nbsp;Macroeconomic indicators</h2><div>Presentation of key macroeconomic indicators</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Annual GDP growth vs. market and model (DFM) estimates",
     "type": "innius-video-panel",
     "description": "We estimated a dynamic factor model (DFM) to provide short-term economic growth forecasts in a timely manner. DFMs are used to exploit useful information from a wide range of high-frequancy indicators. Our model includes monthly data series covering different economic sectors (market services, industry, construction) as well as sentiment, price and labour market indicators. As more information see the light of day, the GDP growth estimates provided by the DFM are expected to become more accurate. The values shown represent the three-month moving average of the annual growth rate.  \n📊 [INS](https://insse.ro/cms/ro), [Reuters](https://www.reuters.com/), own calculation",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Economic heatmap",
     "type": "innius-video-panel",
     "description": "The heat map summarises and presents the evolution of several key macroeconomic indicators in the latest period  \n🟥 worse ◄ 2015-2019 average ► better 🟦",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 54 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Annual GDP growth vs. market and model (DFM) estimates with uncertainty intervals",
     "type": "graph",
     "description": "We estimated a dynamic factor model (DFM) to provide short-term economic growth forecasts in a timely manner. DFMs are used to exploit useful information from a wide range of high-frequancy indicators. Our model includes monthly data series covering different economic sectors (market services, industry, construction) as well as sentiment, price and labour market indicators. As more information see the light of day, the GDP growth estimates provided by the DFM are expected to become more accurate. The values shown represent the three-month moving average of the annual growth rate.  \n📊 [INS](https://insse.ro/cms/ro), [Reuters](https://www.reuters.com/), own calculation",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "macro",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "Range68" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Financial market reactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
     "content": "<p><h2><i class=\"fa fa-line-chart\"></i>&nbsp;&nbsp;Financial market reactions</h2><div>The main developed and regional stock market index closing prices, returns and volatility. The corresponding values for the critical period of the 2008 crisis for comparison (starting dates 📆 2008-09-16 and 2020-02-26 📆).</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Active COVID19 cases",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "BET close",
     "type": "graph",
     "description": "Daily close of the BET index in Bucharest  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "BET" }
       ]
      }
     ]
    },
    {
     "title": "FTSE100 close",
     "type": "graph",
     "description": "Daily close of the FTSE 100 stock index in London  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "FTSE 100" }
       ]
      }
     ]
    },
    {
     "title": "SP500 close",
     "type": "graph",
     "description": "Daily close of the SP500 index in New York  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "S&P 500" }
       ]
      }
     ]
    },
    {
     "title": "Stoxx600 close",
     "type": "graph",
     "description": "Daily close of the Stoxx 600 european stock index  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX" }
       ]
      }
     ]
    },
    {
     "title": "DAX close",
     "type": "graph",
     "description": "Daily close of the Frankfurt-based DAX stock index  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX" }
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "global3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "ww" }
       ]
      },
      {
       "alias": "Romania",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
       ]
      }
     ]
    },
    {
     "title": "BET volatility",
     "type": "graph",
     "description": "Daily volatility (standard deviation) of the BET index in Bucharest  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "BET volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "FTSE100 volatility",
     "type": "graph",
     "description": "Daily volatility (standard deviation) of the FTSE 100 stock index in London  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "FTSE 100 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "SP500 volatility",
     "type": "graph",
     "description": "Daily volatility (standard deviation) of the SP500 in New York  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "SP500 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "Stoxx600 volatility",
     "type": "graph",
     "description": "Daily volatility (standard deviation) of the Stoxx 600 european stock index  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Stoxx 600 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "DAX volatility",
     "type": "graph",
     "description": "Daily volatility (standard deviation) of the Frankfurt-based DAX index  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "Exchange rates of RON",
     "type": "graph",
     "description": "The evolution of the exchange rate of the romanian leu against the euro and the U.S. dollar starting from the date of the first romanian coronavirus case  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks2",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'EUR - RON (valutaárfolyam)' OR \"stock\" = 'USD - RON (valutaárfolyam)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "EUR - RON (valutaárfolyam)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "USD - RON (valutaárfolyam)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "EUR - PLN (valutaárfolyam)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "EUR - HUF (valutaárfolyam)" }
       ]
      }
     ]
    },
    {
     "title": "The spreads of Romanian treasury bonds",
     "type": "graph",
     "description": "The bid-ask yield spreads of the 6-month and one year romanian treasury bills and of the 3, 5 and 10-year romanian government bonds  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/  AND \"year\" = '2020' AND (\"stock\" = 'Bid/ask 5 ev' OR \"stock\" = 'Bid/ask 12 honap ' OR \"stock\" = 'Bid/ask 6 honap')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 10 ev (%)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "Bid/ask 5 ev (%)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "Bid/ask 3 ev (%)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 12 honap (%)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 6 honap (%)" }
       ]
      }
     ]
    },
    {
     "title": "Oil price",
     "type": "graph",
     "description": "The Brent (Nordic Sea) and WTI (West Texas Intermediate) oil futures prices  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Brent' OR \"stock\" = 'WTI') AND \"year\" = '2020') AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Brent" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "WTI" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      }
     ]
    },
    {
     "title": "Romanian Interbank Offer Rate",
     "type": "graph",
     "description": "The three-month Romanian Interbank Offer Rate  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND \"stock\" = 'ROBOR3M') AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "ROBOR3M" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "cases" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Company measures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
     "content": "<p><h2><i class=\"fa fa-car\"></i>&nbsp;&nbsp;Company measures</h2><div>Reactions of the top 50 Romanian companies to the coronavirus pandemic</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Top 50 companies by revenue (2018, RON)",
     "type": "savantly-heatmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "format": "none",
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firms1",
       "select": [
        [
         { "params": [ "revenue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 50 companies by number of employees (2018)",
     "type": "savantly-heatmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "format": "none",
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firms1",
       "select": [
        [
         { "params": [ "employees" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Company measures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "List of company measures",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 15, "x": 9, "y": 65 },
     "targets": [
      {
       "measurement": "firms2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "name" ], "type": "field" }
        ],
        [
         { "params": [ "event" ], "type": "field" }
        ],
        [
         { "params": [ "type" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Company Facebook activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Company steps",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 79 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "firms3",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "revenue" ], "type": "field" }
        ],
        [
         { "params": [ "sulyos" ], "type": "field" }
        ],
        [
         { "params": [ "teljes_leallas" ], "type": "field" }
        ],
        [
         { "params": [ "reszleges_leallas" ], "type": "field" }
        ],
        [
         { "params": [ "szemelyzet_csok" ], "type": "field" }
        ],
        [
         { "params": [ "home_office" ], "type": "field" }
        ],
        [
         { "params": [ "higenia" ], "type": "field" }
        ],
        [
         { "params": [ "testho" ], "type": "field" }
        ],
        [
         { "params": [ "tamogatas" ], "type": "field" }
        ],
        [
         { "params": [ "uzleti_utak" ], "type": "field" }
        ],
        [
         { "params": [ "adomany" ], "type": "field" }
        ],
        [
         { "params": [ "informalas" ], "type": "field" }
        ],
        [
         { "params": [ "egyebi" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 79 },
     "content": "<table class=\"legend\"><tr><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td> ⛔</td><td>Severity</td></tr><tr><td>🔴</td><td>Complete shut-down</td></tr><tr><td>⭕</td><td>Partial shut-down</td></tr><tr><td>😐</td><td>Reducing staff number (including furlough)</td></tr><tr><td>🏠</td><td>Home office, flexible hours</td></tr><tr><td> 💧</td><td>Hygiene, social distancing</td></tr><tr><td>🌡</td><td>Body temperature tracking</td></tr><tr><td>💲</td><td>Support (e.g. dedicated phone line)</td></tr><tr><td>✈</td><td>Ceasing or limiting business travel</td></tr><tr><td>🎈</td><td>Donation</td></tr><tr><td>ℹ</td><td>Informing</td></tr><tr><td>✖</td><td>Others</td></tr>",
     "targets": [
      { "panelId": 90 }
     ]
    }
   ]
  },
  {
   "title": "Industry effects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "content": "<p><h2><i class=\"fa fa-industry\"></i>&nbsp;&nbsp;Industry effects</h2><div>Expected impact of the coronavirus pandemic on major Romanian industrial sectors</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Most affected industries based on their size and change in GDP",
     "type": "innius-video-panel",
     "description": "Forecasts based on the aggregation of estimated GDP change of subsectors  \n📊 Own calculation",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Quarterly GDP forecast (2021 Q1 vs. 2020 Q4)",
     "type": "innius-video-panel",
     "description": "Quarterly forecast. Base scenario.  \n📊 Own calculation",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
     "targets": [
      { "panelId": 90 }
     ]
    }
   ]
  },
  {
   "title": "Mobility indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 55 },
     "content": "<p><h2><i class=\"fa fa-train\"></i>&nbsp;&nbsp;Mobility indicators</h2><div>Effects of the pandemic on various dimensions of mobility (residential, workplace, transit, shopping, leisure) by county. Because of methodological changes announced by Google, the data are incomplete between 📅 2020.08.17. and 📅 2020.09.11.</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evolution of national mobility",
     "type": "innius-video-panel",
     "description": "Composite index based on Google's mobility data. Is shows the change in mobility of the population, compared to the average between 📅 15th of February - 1st of March. You can change the date using the bottom axis (weekly averages - with week closing dates displayed).  Residential values inverted.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 58 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Change in mobility at county level",
     "type": "graph",
     "description": "Composite index based on Google's mobility data. Is shows the change in mobility of the population, compared to the average between 📅 15th of February - 1st of March. Residential values inverted.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility4",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Change in mobility across various domains",
     "type": "graph",
     "description": "Components of the mobility index based on Google's data. Is shows the change in mobility of the population, compared to the average between 📅 15th of February - 1st of March 2020 and the change in border crossings compared to the same date in 2019.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/), [Romanian Border Police](https://www.politiadefrontiera.ro/ro/main/n-date-deschise-17/?fy=2019&page_no=1&fm=4)",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langindicator",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langindicator" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "border_change" }
       ]
      }
     ]
    },
    {
     "title": "Time spent at home",
     "type": "graph",
     "description": "Mobility index based on Google's data. Is shows the change in mobility of the population in this domain, compared to the average between 📅 15th of February - 1st of March, normalized for each day of the week.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "residential_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Time spent at the workplace",
     "type": "graph",
     "description": "Mobility index based on Google's data. Is shows the change in mobility of the population in this domain, compared to the average between 📅 15th of February - 1st of March.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "workplaces_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Public transit stations",
     "type": "graph",
     "description": "Mobility index based on Google's data. Is shows the change in mobility of the population in this domain, compared to the average between 📅 15th of February - 1st of March.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "transit_stations_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Grocery and pharmacy",
     "type": "graph",
     "description": "Mobility index based on Google's data. Is shows the change in mobility of the population in this domain, compared to the average between 📅 15th of February - 1st of March.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "grocery_and_pharmacy_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Retail and recreation",
     "type": "graph",
     "description": "Mobility index based on Google's data. Is shows the change in mobility of the population in this domain, compared to the average between 📅 15th of February - 1st of March.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "retail_and_recreation_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Parks and nature",
     "type": "graph",
     "description": "Mobility index based on Google's data. Is shows the change in mobility of the population in this domain, compared to the average between 📅 15th of February - 1st of March.  \n📊 Own calculation based on data from [Google](https://www.google.com/covid19/mobility/)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "parks_percent_change_from_baseline"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Real estate market",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
     "content": "<p><h2><i class=\"fa fa-home\"></i>&nbsp;&nbsp;Real estate market</h2><div>Average real estate prices and number of real estate transactions in the largest cities, as well as on country and county levels. The corresponding values for the critical period of the 2008 crisis for comparison (starting dates 📆 December 2019 and 📆 June 2008).</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Average apartment price (€/m²) in the largest Romanian cities",
     "type": "innius-video-panel",
     "description": "Average real estate prices per square meters in euros, by counties  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 59 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Average apartment price (€/m²) in 2020",
     "type": "graph",
     "description": "Average real estate prices per square meters in euros, by counties form January 2020  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "currencyEUR" }
     ],
     "targets": [
      {
       "alias": "$tag_city",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "city" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare3",
       "select": [
        [
         { "params": [ "price" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      }
     ]
    },
    {
     "title": "Average apartment price (€/m²) in 2008",
     "type": "graph",
     "description": "Average real estate prices per square meters in euros, by counties starting from September 2008 for comparison  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "currencyEUR" }
     ],
     "targets": [
      {
       "alias": "$tag_city",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "city" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare3",
       "select": [
        [
         { "params": [ "price" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2008" }
       ]
      }
     ]
    },
    {
     "title": "Monthly change in real estate transactions on national level",
     "type": "innius-video-panel",
     "description": "Change in real estate transactions on both country and county level compared to the average of the period between 📅 December 2019 - February 2020  \n📊 [Romanial National Housing Registry](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 71 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Change in real estate transactions per county",
     "type": "graph",
     "description": "Change in real estate transactions on both country and county level compared to the average of the period between 📅 December 2019 - February 2020  \n📊 [Romanial National Housing Registry](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of real estate transactions per county",
     "type": "graph",
     "description": "The number of real estate transactions on both country and county level ❗ 📈 logarithmic scale  \n📊 [Romanial National Housing Registry](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "content": "<div style=\"width:100%;border-bottom:1px solid #52545C;padding-top:40px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 1, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-ellipsis-h\"></i>&nbsp;&nbsp;Other useful pages</h4><div><ul class=\"other\">\n    <li><a href=\"https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6\" target=\"_blank\">Johns Hopkins - <em>CSSE</em></a></li>\n    <li><a href=\"https://www.worldometers.info/coronavirus/\" target=\"_blank\">Worldometers - <em>Coronavirus</em></a></li>\n    <li><a href=\"https://datelazi.ro/\" target=\"_blank\">Date la Zi - <em>COVID-19</em></a></li>\n    <li><a href=\"https://stirioficiale.ro/\" target=\"_blank\">Știri Oficiale - <em>COVID-19</em></a></li>\n    <li><a href=\"https://instnsp.maps.arcgis.com/apps/opsdashboard/index.html#/5eced796595b4ee585bcdba03e30c127\">INSP - <em>Harta Coronavirus</em></a></li>\n    <li><a href=\"https://coronavirus-esriro.hub.arcgis.com/\" target=\"_blank\">ESRI Romania - <em>COVID19 Hub</em></a></li>\n    <li><a href=\"https://coronavirus.casajurnalistului.ro/\" target=\"_blank\">Casa Jurnalistului - <em>Monitorizare Coronavirus</em></a></li>\n    <li><a href=\"https://www.hartacoronavirus.ro/\" target=\"_blank\">HartaCoronavirus.ro</a></li>\n    <li><a href=\"https://covid.solidaritatea-sanitara.ro/\" target=\"_blank\">Solidaritate Sanitara - <em>Salariați din sănătate infectați</em></a></li>\n    <li><a href=\"https://www.graphs.ro/resources.php\" target=\"_blank\">Graphs.ro - <em>JSON Data</em></a></li>\n    <li><a href=\"https://atlo.team/koronamonitor/\" target=\"_blank\">ATLO - <em>Koronamonitor</em></a></li>\n    <li><a href=\"http://statisztikak.erdelystat.ro/vizualizaciok/erdelyi-koronamonitor/2\" target=\"_blank\">Erd&eacute;lystat - <em>Koronamonitor</em></a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-database\"></i>&nbsp;&nbsp;Data sources</h4><div><ul class=\"other\">\n    <li><a href=\"https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series\" target=\"_blank\">Johns Hopkins University - <em>CSSE</em></a></li>\n    <li><a href=\"https://stirioficiale.ro/\" target=\"_blank\">Știri Oficiale - <em>COVID-19</em></a></li>\n    <li><a href=\"https://www.who.int/\" target=\"_blank\">World Health Organization</a></li>\n    <li><a href=\"https://insse.ro/cms/ro\" target=\"_blank\">Romanian National Institute of Statistics</a></li>\n    <li><a href=\"https://www.mfinante.gov.ro/\" target=\"_blank\">Romanian Ministry of Public Finance</a></li>\n    <li><a href=\"http://mmuncii.ro/j33/index.php/en/\" target=\"_blank\">Romanian Ministry of Labour and Social Protection</a></li>\n    <li><a href=\"http://www.consiliulfiscal.ro/Opinie%20Rectificare%20I%202020.pdf\" target=\"_blank\">Fiscal Council of Romania</a></li>\n    <li><a href=\"https://www.bnr.ro/Home.aspx\" target=\"_blank\">Romanian National Bank</a></li>\n    <li><a href=\"https://ec.europa.eu/info/business-economy-euro/indicators-statistics/economic-databases/business-and-consumer-surveys_en\" target=\"_blank\">European Commission</li>\n    <li><a href=\"https://www.ecb.europa.eu/\" target=\"_blank\">European Central Bank</li>\n    <li><a href=\"https://www.imf.org/external/index.htm\" target=\"_blank\">International Monetary Fund</li><li><a href=\"https://eikon.thomsonreuters.com/index.html\" target=\"_blank\">Thomson Reuters - <em>Eikon</em></a></li>\n    <li><a href=\"https://www.google.com/covid19/mobility/\" target=\"_blank\">Google - <em>COVID-19 Mobility</em></a></li>\n    <li><a href=\"https://www.ancpi.ro/\" target=\"_blank\">Romanial National Housing Registry</a></li>\n    <li><a href=\"https://www.imobiliare.ro/\" target=\"_blank\"><em>Imobiliare.ro</em> index</a></li>\n    <li><a href=\"https://covidtracker.bsg.ox.ac.uk/\" target=\"_blank\">Oxford <em>Government Response Tracker</em></a></li>\n    <li><a href=\"https://www.reuters.com/\" target=\"_blank\"><em>News</em> - Reuters</a>, <a href=\"https://bloomberg.com/\" target=\"_blank\">Bloomberg</a>, <a href=\"https://news.bbc.co.uk/\" target=\"_blank\">BBC</a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-coffee\"></i>&nbsp;&nbsp;Our team</h4><div><ul class=\"credit\">\n    <li><b>B&aacute;lint Csaba&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/csaba-b%C3%A1lint-cfa-16b9a665/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Csala D&eacute;nes&nbsp;<a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/csaladenes/\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a><a title=\"Email\"\n                href=\"mailto:mail@csaladen.es\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa\n            fa-envelope\"></i></a></b></li>\n    <li><b>Cs&iacute;ki Ott&oacute;&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/ott%C3%B3-cs%C3%ADki-a01820109/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Nagy B&aacute;lint Zsolt&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/balint-zsolt-nagy-phd-8796621/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>R&aacute;cz B&eacute;la-Gergely&nbsp;<a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/raczbela/\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Sz&aacute;sz Levente <a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/leventeszasz/\" target=\"_blank\"\n                rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a><a title=\"Email\" href=\"mailto:levente.szasz@econ.ubbcluj.ro\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa\n            fa-envelope\"></i></a></b></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 65 },
   "content": "<p><h4><i class=\"fa fa-trophy\"></i>&nbsp;&nbsp;Our prizes</h4><div><ul class=\"other\">\n    <li><a href=\"https://cgdv.github.io/challenges/COVID-19/results1.html\" target=\"_blank\">Flattening the curve<i> - COVID-19 Data Challenge</i></a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "content": "<div style=\"width:100%;border-bottom:1px solid #52545C;padding-top:0px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "innius-video-panel",
   "gridPos": { "h": 4, "w": 7, "x": 1, "y": 72 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "innius-video-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 72 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 72 },
   "content": "<p><h4><i class=\"fa fa-pencil\"></i>&nbsp;&nbsp;Citation</h4><div>UBB-FSEGA (2020): COVID-19 - Romanian Economic Impact Monitor, https://econ.ubbcluj.ro/coronavirus/, last accessed on: 2021-04-01</div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "content": "<div style=\"width:100%;border-bottom:1px solid #52545C;padding-top:0px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 1, "y": 77 },
   "content": "<a target=\"_blank\" href=\"https://www.ubbcluj.ro/en/\"><img id=\"logo\" class=\"logo\" alt=\"Babeș-Bolyai University\" src=\"//covid-large-html.csaladen.es/img/logo_UBB_en.png\" style=\"height:70px!important;width:200px!important;\"/></a>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 77 },
   "content": "<br><div class=\"lang\" style=\"text-align:left;\">Copyright &copy; 2021 | <a target=\"_blank\" href=\"https://www.ubbcluj.ro/en/\">Babeș-Bolyai University</a> | <a target=\"_blank\" href=\"https://econ.ubbcluj.ro/\">FSEGA</a></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 77 },
   "content": "<br><div class=\"lang\" style=\"text-align:left;\">The visualizations were created using <a target=\"_blank\" href=\"http://grafana.org/\"><img src=\"https://grafana.com/favicon.ico\" style=\"height:20px;width:20px;margin-bottom:0px;\">&nbsp;Grafana</a> by <a target=\"_blank\" href=\"https://www.csaladen.es/\"><img src=\"https://www.csaladen.es/favicon.ico\" style=\"height:20px;width:20px;margin-bottom:-1px;\">&nbsp;Dénes Csala</a></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
   "content": "<div style=\"width:100%;padding-top:20px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  }
 ]
}