{
 "title": "Magyar",
 "time": { "from": "now-381d", "to": "now+14d" },
 "templating": {
  "list": [
   { "name": "lang", "query": "HU,RO,EN" },
   { "name": "theme", "query": "dark,light" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "content": "<a target=\"_blank\" href=\"https://econ.ubbcluj.ro/\"><img id=\"flogo\" class=\"flogo\" alt=\"Babeș-Bolyai Tudományegyetem\" src=\"//covid-large-html.csaladen.es/img/fsega_hu.png\" style=\"height:80px!important;width:330px!important;\"/></a>"
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 1, "x": 7, "y": 0 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 0 },
   "content": "<div style=\"text-align:left;\"><h1>COVID-19 – Romanian Economic Impact Monitor</h1><h3> A koronavírus-járvány hatásai a román gazdaságra: tények és előrejelzések</h3></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "content": "<br><div class=\"lang\" style=\"text-align: center; font-size:16px;\">&nbsp;&nbsp;<a target=\"_self\" title=\"Română\" href=\"/d/ro\">RO</a>&nbsp;&nbsp;<a target=\"_self\" title=\"Magyar\" href=\"/d/hu\">HU</a>&nbsp;&nbsp;<a target=\"_self\" title=\"English\" href=\"/d/en\">EN</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"fa fa-paint-brush\"></i>&nbsp;&nbsp;<a target=\"_self\" title=\"Sötét kinézet\" href=\"/d/hu\"><i class=\"fa fa-circle\"></i></a>&nbsp;&nbsp;<a target=\"_self\" title=\"Világos kinézet\" href=\"/d/hu-light?theme=light\"><i class=\"fa fa-circle-o\"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style=\"font-size:20px;\" target=\"_blank\" title=\"Facebook\" href=\"https://www.facebook.com/covid19.roeim\"><i class=\"fa fa-facebook\"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style=\"font-size:20px;\" target=\"_blank\" title=\"Help\" href=\"https://github.com/denesdata/covid19-romania/wiki\"><i class=\"fa fa-question\"></i></a></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    },
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 5 },
   "content": "<p><span style=\"font-size:18px;\"><span style=\"font-size:26px;color:#F2CC0C;\"><b>433</b></span> nap telt el az első koronavírus eset óta Romániában és jelenleg <span style=\"font-size:26px;color:#ff780a;\"><b>27&nbsp;265</b></span> aktív eset van.</span></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Fertőzöttségi arány településenként 📆 2021 május 3",
   "type": "innius-video-panel",
   "description": "🕑 Frissült 2021 május 3-án, 10:34-kor\n  \nFertőzöttségi arány (utóbbi két hét új eseteinek összege/1000 lakos - a megjelenített dátum előtti 17 és 3 napok közötii időszakban) településenként (közigazgatási egységenként UAT)   \n  \n📊 [data.gov.ro](https://data.gov.ro/dataset/transparenta-covid)",
   "gridPos": { "h": 13, "w": 1, "x": 7, "y": 5 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Összes eset",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gyógyultak",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "heals" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elhunytak",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Beoltottak száma",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "total_immunized" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"base\".\"vaccine1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'total_immunized' OR \"type\" = 'total_first')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "content": "A Babeș-Bolyai Tudományegyetem Közgazdaság- és Gazdálkodástudományi Karának kutatási projektje, melyben a kutatócsoport tagjai naponta közzéteszik elemzéseiket a koronavírus-járvány romániai gazdasági hatásaira nézve. A naponta frissített, interaktív infografikák segítségével egy átfogó és tiszta képet kívánunk nyújtani az aktuális gazdasági helyzetről Romániában.\nWeboldalunk célja, hogy segítséget nyújtson a gazdasági és politikai döntéshozóknak azáltal, hogy tényadatokra alapozva, folyamatosan frissítve ismerteti az aktuális helyzetet és támpontot nyújtson a romániai előrejelzési szcenáriók kialakításához a társadalom, az alkalmazottak, a vállalatok és az ellátási láncok védelme érdekében.",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Éves GDP előrejelzés (2021)",
   "type": "singlestat",
   "description": "Éves előrejelzés. Alapforgatókönyv.  \n📊 Saját számítás",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "gdp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Negyedéves GDP előrejelzés (2021 Q1 vs. 2020 Q4)",
   "type": "singlestat",
   "description": "Negyedéves előrejelzés. Alapforgatókönyv.  \n📊 Saját számítás",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "gdpq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "EUR-RON árfolyamának változása",
   "type": "singlestat",
   "description": "EUR-RON árfolyamának összesített változása az első Covid-19-es eset bejelentése óta (📅 február 26).  \n📊 Saját számítás [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html) adatok alapján",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "xch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BET index értékváltozása",
   "type": "singlestat",
   "description": "BET index értékváltozása  az első Covid-19-es eset bejelentése óta (📅 február 26).  \n📊 Saját számítás [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html) adatok alapján",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "bet" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Előrejelzett éves költségvetési hiány (2021)",
   "type": "singlestat",
   "description": "  \n📊 [Romániai Költségvetési Tanács](http://www.consiliulfiscal.ro/Opinie%20CF%20buget%202021%20si%20SFB.pdf)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "status_plot14" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alkalmazottak számának változása",
   "type": "singlestat",
   "description": "2019 átlagához (=100) viszonyítva, szezonálisan  \n📊 [INS](https://insse.ro/cms/ro)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "employees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Munkanélküliség",
   "type": "singlestat",
   "description": "  \n📊 [INS](https://insse.ro/cms/ro)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "unemployment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Google mobilitás index",
   "type": "singlestat",
   "description": "Összetett mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása. Lakóövezetek inverzként számolva.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "mobility_mini" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "content": "<div style=\"text-align:right;\"><i class=\"fa fa-clock-o\"></i>&nbsp;Az adatok naponta <b>14:00</b> órakor frissülnek. Utolsó frissítés: <b>2021.05.03</b></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  { "title": "Helyzetjelentés", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Fertőzöttségi arány településenként 📆 2021 május 3",
   "type": "innius-video-panel",
   "description": "🕑 Frissült 2021 május 3-án, 10:34-kor\n  \nFertőzöttségi arány (utóbbi két hét új eseteinek összege/1000 lakos - a megjelenített dátum előtti 17 és 3 napok közötii időszakban) településenként (közigazgatási egységenként UAT)   \n  \n📊 [data.gov.ro](https://data.gov.ro/dataset/transparenta-covid)",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Beadott első oltás-adagok (+) és beoltottak (-)",
   "type": "graph",
   "description": "Beadott első oltás-adagok oltástípusok szerint (pozitív irányban) és a beoltottak száma, oltástípusok szerint (negatív irányban)  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vaccine1",
     "query": "SELECT mean(\"value\") FROM \"base\".\"vaccine1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'total_administered' OR \"type\" = 'total_administered_astra_zeneca' OR \"type\" = 'total_administered_pfizer' OR \"type\" = 'total_administered_moderna')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered" },
      {
       "condition": "AND",
       "key": "type",
       "operator": "!=",
       "value": "total_administered_astra_zeneca"
      },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered_moderna" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered_pfizer" }
     ]
    }
   ]
  },
  {
   "title": "Rövid távú előrejelzés a napi esetszámokra",
   "type": "graph",
   "description": "  \n📊 Saját becslés, hetente frissül",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    }
   ]
  },
  {
   "title": "Fertőzöttségi arány változása megyénként (utóbbi két hét új eseteinek összege/1000 lakos)",
   "type": "heatmap",
   "description": "Fertőzöttségi arány változása megyénként (utóbbi két hét új eseteinek összege/1000 lakos)  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/), Saját becslés",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "county" ], "type": "tag" }
     ],
     "measurement": "counties3",
     "select": [
      [
       { "params": [ "case_14_cap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
     ]
    }
   ]
  },
  {
   "title": "Esetek, gyógyulások és elhalálozások összesen",
   "type": "graph",
   "description": "Minden adat a kormány által közölt hivatalos forrásból származik. Az aktív esetek egy számolt mérték, ezeket kétféle módon számoljuk: Az <b>Aktív esetek (saját becslés)</b> az utóbbi 14 nap új eseteinek összege, a <b>Aktív esetek (hivatalos)</b> az Összes esetekből kivont Elhalálozások és Gyógyulások száma.  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/)",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance1",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
     ]
    }
   ]
  },
  {
   "title": "Esetek, gyógyulások és elhalálozások napi változása",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "case/test" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "death_rate" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "case/test" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "death_rate" }
     ]
    }
   ]
  },
  {
   "title": "Pozitív tesztek aránya és elhalálozási arány",
   "type": "graph",
   "description": "A pozitív tesztek arányát a napi új esetek számát elosztva a napi tesztek számával kapjuk. Az elhalálozási arányt a napi új elhalálozásokat elosztva a napi új esetek számával kapjuk.  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/), [Johns Hopkins Egyetem - CSSE](https://coronavirus.jhu.edu/data/mortality)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"base\".\"governance2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'case/test' OR \"type\" = 'death_rate')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case/test" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "death_rate" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT moving_average(mean(\"value\"), 14) FROM \"base\".\"governance2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'death_rate' OR \"type\" = 'case/test')) AND $timeFilter GROUP BY time(1d), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "death_rate" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "case/test" }
     ]
    }
   ]
  },
  {
   "title": "Hírek",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 },
     "content": "<p><h2><i class=\"fa fa-newspaper-o\"></i>&nbsp;&nbsp;Hírek</h2><div>Friss hírek a projekt csapatától, médiamegjelenések, illetve hivatalos kormányzati hírek és bejelentések</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Facebook bejegyzéseink",
     "type": "innius-video-panel",
     "description": "  \n📊 [COVID-19 Romanian Economic Impact Monitor Hivatalos Facebook Oldal](https://www.facebook.com/covid19.roeim)",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 51 },
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "counties2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Médiamegjelenések",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 51 },
     "targets": [
      {
       "measurement": "global2",
       "query": "SELECT  \"media\", \"desc\", \"lang\",\"type\", \"link\" FROM \"base\".\"news1\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Globális események",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
     "content": "<p><h2><i class=\"fa fa-globe\"></i>&nbsp;&nbsp;Globális események</h2><div>A legfontosabb globális jelentőségű gazdasági, társadalmi események és intézkedések</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Aktív esetek alakulása a világon",
     "type": "graph",
     "description": "❗ 📈 logaritmikus skála  \n📊 [Johns Hopkins Egyetem - CSSE](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "global3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      },
      {
       "alias": "Románia (hivatalos)",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "active" }
       ]
      },
      {
       "alias": "Románia (saját becslés)",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
       ]
      }
     ]
    },
    {
     "title": "Globális események",
     "type": "table-old",
     "description": "A legfontosabb globális jelentőségű gazdasági, társadalmi események és intézkedések  \n📊 [Reuters](https://www.reuters.com/), [Bloomberg](https://bloomberg.com/), [BBC](https://news.bbc.co.uk/), [WHO](https://www.who.int/), [EKB](https://www.ecb.europa.eu/), [IMF](https://www.imf.org/external/index.htm), [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "measurement": "global2",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Kormányzati intézkedések",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
     "content": "<p><h2><i class=\"fa fa-gavel\"></i>&nbsp;&nbsp;Kormányzati intézkedések</h2><div>Kormányzati társadalmi és gazdasági intézkedések összefoglalója</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "A kormányzati intézkedések szigorának alakulása Romániában és más országokban",
     "type": "graph",
     "description": "Az intézkedések szigora egy 0 (enyhe) - 100 (szigorú) közötti relatív mutató.  \n📊 [Oxfordi Egyetem - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langcountry",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langcountry" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "severity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "lang2", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "stringency" }
       ]
      }
     ]
    },
    {
     "title": "Lakossági válasz a kormányzati intézkedések szigorára",
     "type": "innius-video-panel",
     "description": "Az intézkedések szigora egy 0 (enyhe) - 100 (szigorú) közötti relatív mutató.  \n📊 [Oxfordi Egyetem - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 53 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "A kormányzati intézkedések szigora és a lakossági mobilitás csökkenése a napi új esetek mellett",
     "type": "graph",
     "description": "A lakosság mobilitása és a kormányzati intézkedések szigora egy 0-100 közötti relatív mutató. A mobilitás fordított értékkel szerepel!  \n📊 [Oxfordi Egyetem - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "severity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "lang2", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "country", "operator": "=", "value": "ro" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "stringency" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
       ]
      },
      {
       "alias": "Mobilitás-csökkenés",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance3",
       "select": [
        [
         { "params": [ "mobility_mini" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Gazdasági intézkedések",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Gazdasági intézkedések listája",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 64 },
     "targets": [
      {
       "measurement": "social1",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social1\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "desc2" ], "type": "field" }
        ],
        [
         { "params": [ "desc3" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Társadalmi intézkedések",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Társadalmi intézkedések listája",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 71 },
     "targets": [
      {
       "measurement": "social2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social2\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Pénzügyi intézkedések",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Pénzügyi intézkedések listája",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 78 },
     "targets": [
      {
       "measurement": "global2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Makrogazdasági mutatók",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 },
     "content": "<p><h2><i class=\"fa fa-forward\"></i>&nbsp;&nbsp;Makrogazdasági mutatók</h2><div>Kiemelt makrogazdasági mutatók összefoglalója</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Éves GDP-növekedés vs. piaci és modell (DFM) becslések",
     "type": "innius-video-panel",
     "description": "Egy dinamikus faktor modellt (DFM) becsültünk minél aktuálisabb rövid távú gazdasági növekedési előrejelzések készítéséhez. A DFM-eket rendszerint arra használják, hogy hasznos információt vonjon ki széles skálából származó és nagyobb gyakorisággal publikált adatsorokból. Modellünk havi indikátorokat tartalmaz számos gazdasági ágazatról (piaci szolgáltatások, ipar, építőipar), illetve gazdasági szentiment, ár és a munkaerő-piaci mutatókat is figyelembe vesz. Az idő múlásával, ahogyan egyre több információ kerül napvilágra, a DFM által szolgáltatott GDP növekedési becslések várhatóan pontosabbaká válnak. A feltüntetett értékek az éves növekedési ütem három havi mozgó átlagát mutatják.  \n📊 [INS](https://insse.ro/cms/ro), [Reuters](https://www.reuters.com/), saját számítás",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Gazdasági hőtérkép",
     "type": "innius-video-panel",
     "description": "A hőtérkép összegzi és bemutatja számos kiemelt makrogazdasági mutató alakulását a legutóbbi időszakban  \n🟥 rosszabb ◄ 2015-2019-es átlag ► jobb 🟦",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 54 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Éves GDP-növekedés vs. piaci és modell (DFM) becslések bizonytalansági sávokkal",
     "type": "graph",
     "description": "Egy dinamikus faktor modellt (DFM) becsültünk minél aktuálisabb rövid távú gazdasági növekedési előrejelzések készítéséhez. A DFM-eket rendszerint arra használják, hogy hasznos információt vonjon ki széles skálából származó és nagyobb gyakorisággal publikált adatsorokból. Modellünk havi indikátorokat tartalmaz számos gazdasági ágazatról (piaci szolgáltatások, ipar, építőipar), illetve gazdasági szentiment, ár és a munkaerő-piaci mutatókat is figyelembe vesz. Az idő múlásával, ahogyan egyre több információ kerül napvilágra, a DFM által szolgáltatott GDP növekedési becslések várhatóan pontosabbaká válnak. A feltüntetett értékek az éves növekedési ütem három havi mozgó átlagát mutatják.  \n📊 [INS](https://insse.ro/cms/ro), [Reuters](https://www.reuters.com/), saját számítás",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "macro",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "Range68" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "A pénzügyi piacok reakciói",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
     "content": "<p><h2><i class=\"fa fa-line-chart\"></i>&nbsp;&nbsp;A pénzügyi piacok reakciói</h2><div>A legfontosabb fejlett és régiónkbeli tőzsdeindexek záróértékei, hozama (változása) és volatilitása. Összehasonlításképpen a 2008-as válság kritikus időszakának értékei (kezdődátumok: 📆 2008-09-16, illetve 2020-02-26 📆).</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Aktív COVID19 esetek",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "BET záró",
     "type": "graph",
     "description": "A bukaresti BET tőzsdeindex napi záróértéke  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "BET" }
       ]
      }
     ]
    },
    {
     "title": "FTSE100 záró",
     "type": "graph",
     "description": "A FTSE 100 londoni tőzsdeindex napi záróértéke  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "FTSE 100" }
       ]
      }
     ]
    },
    {
     "title": "SP500 záró",
     "type": "graph",
     "description": "A Standard and Poor's 500 New York-i tőzsdeindex napi záróértéke  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "S&P 500" }
       ]
      }
     ]
    },
    {
     "title": "Stoxx600 záró",
     "type": "graph",
     "description": "A Stoxx 600 páneurópai tőzsdeindex napi záróértéke  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX" }
       ]
      }
     ]
    },
    {
     "title": "DAX záró",
     "type": "graph",
     "description": "A frankfurti DAX tőzsdeindex napi záróértéke  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX" }
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "global3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "ww" }
       ]
      },
      {
       "alias": "Románia",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
       ]
      }
     ]
    },
    {
     "title": "BET volatilitás",
     "type": "graph",
     "description": "A bukaresti BET tőzsdeindex napi hozamainak volatilitása (szórása)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "BET volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "FTSE100 volatilitás",
     "type": "graph",
     "description": "A FTSE 100 londoni tőzsdeindex napi hozamainak volatilitása (szórása)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "FTSE 100 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "SP500 volatilitás",
     "type": "graph",
     "description": "A Standard and Poor's 500 New York-i tőzsdeindex napi hozamainak volatilitása (szórása)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "SP500 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "Stoxx600 volatilitás",
     "type": "graph",
     "description": "A Stoxx 600 páneurópai tőzsdeindex napi hozamainak volatilitása (szórása)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Stoxx 600 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "DAX volatilitás",
     "type": "graph",
     "description": "A frankfurti DAX tőzsdeindex napi hozamainak volatilitása (szórása)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "RON deviza-árfolyam-változás",
     "type": "graph",
     "description": "A román lej euróval és amerikai dollárral szembeni devizaárfolyamának változása az első romániai koronavírus fertőzéstől kezdődően  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks2",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'EUR - RON (valutaárfolyam)' OR \"stock\" = 'USD - RON (valutaárfolyam)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "EUR - RON (valutaárfolyam)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "USD - RON (valutaárfolyam)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "EUR - PLN (valutaárfolyam)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "EUR - HUF (valutaárfolyam)" }
       ]
      }
     ]
    },
    {
     "title": "Román állampapír spreadek",
     "type": "graph",
     "description": "A romániai 6 hónapos és egy éves kincstárjegy valamint a 3, 5 és 10 éves államkötvények vételi és eladási hozama közötti különbözet.   \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/  AND \"year\" = '2020' AND (\"stock\" = 'Bid/ask 5 ev' OR \"stock\" = 'Bid/ask 12 honap ' OR \"stock\" = 'Bid/ask 6 honap')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 10 ev (%)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "Bid/ask 5 ev (%)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "Bid/ask 3 ev (%)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 12 honap (%)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 6 honap (%)" }
       ]
      }
     ]
    },
    {
     "title": "Kőolajár",
     "type": "graph",
     "description": "A Brent (északi tengeri) és a WTI (West Texas Intermediate) kőolaj futures árfolyama  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Brent' OR \"stock\" = 'WTI') AND \"year\" = '2020') AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Brent" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "WTI" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      }
     ]
    },
    {
     "title": "Romániai bankközi kamatláb",
     "type": "graph",
     "description": "A 3 hónapos romániai bankközi kamatláb  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND \"stock\" = 'ROBOR3M') AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "ROBOR3M" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "cases" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Vállalati intézkedések",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
     "content": "<p><h2><i class=\"fa fa-car\"></i>&nbsp;&nbsp;Vállalati intézkedések</h2><div>Románia 50 legnagyobb vállalatának reakciói a koronavírus-járványra</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "A legnagyobb 50 cég üzleti forgalom (2018, RON) szerinti eloszlása",
     "type": "savantly-heatmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "format": "none",
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firms1",
       "select": [
        [
         { "params": [ "revenue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "A legnagyobb 50 cég alkalmazottak száma (2018, fő) szerinti eloszlása",
     "type": "savantly-heatmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "format": "none",
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firms1",
       "select": [
        [
         { "params": [ "employees" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Vállalati intézkedések",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Vállalati intézkedések listája",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 15, "x": 9, "y": 65 },
     "targets": [
      {
       "measurement": "firms2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "name" ], "type": "field" }
        ],
        [
         { "params": [ "event" ], "type": "field" }
        ],
        [
         { "params": [ "type" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Vállalati Facebook-aktivitás",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "A vállalat lépése(i)",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 79 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "firms3",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "revenue" ], "type": "field" }
        ],
        [
         { "params": [ "sulyos" ], "type": "field" }
        ],
        [
         { "params": [ "teljes_leallas" ], "type": "field" }
        ],
        [
         { "params": [ "reszleges_leallas" ], "type": "field" }
        ],
        [
         { "params": [ "szemelyzet_csok" ], "type": "field" }
        ],
        [
         { "params": [ "home_office" ], "type": "field" }
        ],
        [
         { "params": [ "higenia" ], "type": "field" }
        ],
        [
         { "params": [ "testho" ], "type": "field" }
        ],
        [
         { "params": [ "tamogatas" ], "type": "field" }
        ],
        [
         { "params": [ "uzleti_utak" ], "type": "field" }
        ],
        [
         { "params": [ "adomany" ], "type": "field" }
        ],
        [
         { "params": [ "informalas" ], "type": "field" }
        ],
        [
         { "params": [ "egyebi" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 79 },
     "content": "<table class=\"legend\"><tr><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td> ⛔</td><td>Súlyosság</td></tr><tr><td>🔴</td><td>Teljes leállás</td></tr><tr><td>⭕</td><td>Részleges leállás</td></tr><tr><td>😐</td><td>Személyzet csökkentése (akár technikai munkanélküliséggel)</td></tr><tr><td>🏠</td><td>Home office, rugalmas munkaidő</td></tr><tr><td> 💧</td><td>Higiénia, távolságtartás</td></tr><tr><td>🌡</td><td>Testhőmérséklet követése</td></tr><tr><td>💲</td><td>Támogatás (pl. telefonos vonal stb.)</td></tr><tr><td>✈</td><td>Üzleti utak leállítása vagy korlátozása</td></tr><tr><td>🎈</td><td>Adomány</td></tr><tr><td>ℹ</td><td>Informálás</td></tr><tr><td>✖</td><td>Egyéb</td></tr>",
     "targets": [
      { "panelId": 90 }
     ]
    }
   ]
  },
  {
   "title": "Iparági hatások",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "content": "<p><h2><i class=\"fa fa-industry\"></i>&nbsp;&nbsp;Iparági hatások</h2><div>A koronavírus-járvány várható hatásai Románia legfontosabb iparágaira</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Legjobban érintett iparágak méret és GDP változás szerint",
     "type": "innius-video-panel",
     "description": "Előrejelzés az alágazatok becsült GDP változásának aggregálása alapján  \n📊 Saját számítás",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Negyedéves GDP előrejelzés (2021 Q1 vs. 2020 Q4)",
     "type": "innius-video-panel",
     "description": "Negyedéves előrejelzés. Alapforgatókönyv.  \n📊 Saját számítás",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
     "targets": [
      { "panelId": 90 }
     ]
    }
   ]
  },
  {
   "title": "Mobilitási mutatók",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 55 },
     "content": "<p><h2><i class=\"fa fa-train\"></i>&nbsp;&nbsp;Mobilitási mutatók</h2><div>A járvány mobilitás szempontjából lakosságra kifejtett hatása, több dimenzióban (otthon, munkahely, tömegközlekedés, bevásárlás, kikapcsolódás), megyénként. A Google módszertani módosításai miatt az adatok 📅 2020.08.15 és 📅 2020.09.11 között hiányosak .</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Országos mobilitás alakulása",
     "type": "innius-video-panel",
     "description": "Összetett mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása. Az alsó tengely segítségével változtatható a dátum (heti átlagok - a megjelenített dátumokkal záródóan).  Lakóövezetek inverzként számolva.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 58 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "A mobilitás változása megyék szerint",
     "type": "graph",
     "description": "Összetett mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása.  Lakóövezetek inverzként számolva.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility4",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "A mobilitás változása aktivitási területek szerint",
     "type": "graph",
     "description": "A mobilitás index komponensei a Google adatai alapján. Megmutatja, hogy a 📅 2020 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása, illetve a határátkelések száma a 2019-es év ugyanazon napjához viszonyítva.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján, [Romániai Határrendőrség](https://www.politiadefrontiera.ro/ro/main/n-date-deschise-17/?fy=2019&page_no=1&fm=4)",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langindicator",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langindicator" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "border_change" }
       ]
      }
     ]
    },
    {
     "title": "Lakóövezetek",
     "type": "graph",
     "description": "Mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása ezen az aktivitási területen, normalizálva a hét napjaira.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "residential_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Munkahelyek",
     "type": "graph",
     "description": "Mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása ezen az aktivitási területen.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "workplaces_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Tömegközlekedési állomások",
     "type": "graph",
     "description": "Mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása ezen az aktivitási területen.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "transit_stations_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Élelmiszerüzletek és gyógyszertárak",
     "type": "graph",
     "description": "Mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása ezen az aktivitási területen.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "grocery_and_pharmacy_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Kiskereskedelem és szabadidő",
     "type": "graph",
     "description": "Mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása ezen az aktivitási területen.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "retail_and_recreation_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Parkok",
     "type": "graph",
     "description": "Mobilitás index a Google adatai alapján. Megmutatja, hogy a 📅 február 15 - március 1 időszakhoz képest mennyit változott a lakosság átlagos mobilitása ezen az aktivitási területen.  \n📊 Saját számítás [Google](https://www.google.com/covid19/mobility/?hl=hu) adatok alapján",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "parks_percent_change_from_baseline"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ingatlanpiac",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
     "content": "<p><h2><i class=\"fa fa-home\"></i>&nbsp;&nbsp;Ingatlanpiac</h2><div>Ingatlan átlagárak és adásvételek változása a nagyvárosokban, illetve országos és megyei szinten. Összehasonlításképpen a 2008-as válság kritikus időszakának értékei (kezdődátumok: 📆 2019 december, illetve 📆 2008 június).</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Négyzetméterenkénti átlagos lakásár (€/m²) az ország nagyvárosaiban",
     "type": "innius-video-panel",
     "description": "Ingatlan átlagárak euróban négyzetméterre vetítve, megyei bontásban  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 59 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Négyzetméterenkénti átlagos lakásár (€/m²) 2020-ban",
     "type": "graph",
     "description": "Ingatlan átlagárak euróban négyzetméterre vetítve, megyei bontásban, 2020 januárjától  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "currencyEUR" }
     ],
     "targets": [
      {
       "alias": "$tag_city",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "city" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare3",
       "select": [
        [
         { "params": [ "price" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      }
     ]
    },
    {
     "title": "Négyzetméterenkénti átlagos lakásár (€/m²) 2008-ban",
     "type": "graph",
     "description": "Ingatlan átlagárak euróban négyzetméterre vetítve, megyei bontásban, összehasonlításképpen 2008 szeptembertől  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "currencyEUR" }
     ],
     "targets": [
      {
       "alias": "$tag_city",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "city" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare3",
       "select": [
        [
         { "params": [ "price" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2008" }
       ]
      }
     ]
    },
    {
     "title": "Ingatlan adásvételek számának havi változása országszerte",
     "type": "innius-video-panel",
     "description": "Ingatlan adásvételek számának változása országos és megyei szinten a 📅 2019 december - 2020 február átlagához képest   \n📊 [Román Nemzeti Kataszteri Hivatal](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 71 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Ingatlan adásvételek változása megyénként",
     "type": "graph",
     "description": "Ingatlan adásvételek számának változása országos és megyei szinten a 📅 2019 december - 2020 február átlagához képest   \n📊 [Román Nemzeti Kataszteri Hivatal](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Ingatlan adásvételek száma megyénként",
     "type": "graph",
     "description": "Ingatlan adásvételek száma országos és megyei szinten ❗ 📈 logaritmikus skála  \n📊 [Román Nemzeti Kataszteri Hivatal](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "content": "<div style=\"width:100%;border-bottom:1px solid lightGray;padding-top:40px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 1, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-ellipsis-h\"></i>&nbsp;&nbsp;Más hasznos oldalak</h4><div><ul class=\"other\">\n    <li><a href=\"https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6\" target=\"_blank\">Johns Hopkins - <em>CSSE</em></a></li>\n    <li><a href=\"https://www.worldometers.info/coronavirus/\" target=\"_blank\">Worldometers - <em>Coronavirus</em></a></li>\n    <li><a href=\"https://datelazi.ro/\" target=\"_blank\">Date la Zi - <em>COVID-19</em></a></li>\n    <li><a href=\"https://stirioficiale.ro/\" target=\"_blank\">Știri Oficiale - <em>COVID-19</em></a></li>\n    <li><a href=\"https://instnsp.maps.arcgis.com/apps/opsdashboard/index.html#/5eced796595b4ee585bcdba03e30c127\">INSP - <em>Harta Coronavirus</em></a></li>\n    <li><a href=\"https://coronavirus-esriro.hub.arcgis.com/\" target=\"_blank\">ESRI Romania - <em>COVID19 Hub</em></a></li>\n    <li><a href=\"https://coronavirus.casajurnalistului.ro/\" target=\"_blank\">Casa Jurnalistului - <em>Monitorizare Coronavirus</em></a></li>\n    <li><a href=\"https://www.hartacoronavirus.ro/\" target=\"_blank\">HartaCoronavirus.ro</a></li>\n    <li><a href=\"https://covid.solidaritatea-sanitara.ro/\" target=\"_blank\">Solidaritate Sanitara - <em>Salariați din sănătate infectați</em></a></li>\n    <li><a href=\"https://www.graphs.ro/resources.php\" target=\"_blank\">Graphs.ro - <em>JSON Data</em></a></li>\n    <li><a href=\"https://atlo.team/koronamonitor/\" target=\"_blank\">ATLO - <em>Koronamonitor</em></a></li>\n    <li><a href=\"http://statisztikak.erdelystat.ro/vizualizaciok/erdelyi-koronamonitor/2\" target=\"_blank\">Erd&eacute;lystat - <em>Koronamonitor</em></a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-database\"></i>&nbsp;&nbsp;Adatforrások</h4><div><ul class=\"other\">\n    <li><a href=\"https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series\" target=\"_blank\">Johns Hopkins Egyetem - <em>CSSE</em></a></li>\n    <li><a href=\"https://stirioficiale.ro/\" target=\"_blank\">Știri Oficiale - <em>COVID-19</em></a></li>\n    <li><a href=\"https://www.who.int/\" target=\"_blank\">Egészségügyi Világszervezet</a></li>\n    <li><a href=\"https://insse.ro/cms/ro\" target=\"_blank\">Román Nemzeti Statisztikai Hivatal</a></li>\n    <li><a href=\"https://www.mfinante.gov.ro/\" target=\"_blank\">Román Államháztartási Minisztérium</a></li>\n    <li><a href=\"http://mmuncii.ro/j33/index.php/ro/\" target=\"_blank\">Román Munkaügyi Minisztérium</a></li>\n    <li><a href=\"http://www.consiliulfiscal.ro/Opinie%20Rectificare%20I%202020.pdf\" target=\"_blank\">Románia Költségvetési Tanácsa</a></li>\n    <li><a href=\"https://www.bnr.ro/Home.aspx\" target=\"_blank\">Román Nemzeti Bank</a></li>\n    <li><a href=\"https://ec.europa.eu/info/business-economy-euro/indicators-statistics/economic-databases/business-and-consumer-surveys_en\" target=\"_blank\">Európai Bizottság</li>\n    <li><a href=\"https://www.ecb.europa.eu/\" target=\"_blank\">Európai Központi Bank</li>\n    <li><a href=\"https://www.imf.org/external/index.htm\" target=\"_blank\">Nemzetközi Valutaalap</li><li><a href=\"https://eikon.thomsonreuters.com/index.html\" target=\"_blank\">Thomson Reuters - <em>Eikon</em></a></li>\n    <li><a href=\"https://www.google.com/covid19/mobility/\" target=\"_blank\">Google - <em>COVID-19 Mobilitás</em></a></li>\n    <li><a href=\"https://www.ancpi.ro/\" target=\"_blank\">Román Nemzeti Kataszteri Hivatal</a></li>\n    <li><a href=\"https://www.imobiliare.ro/\" target=\"_blank\"><em>Imobiliare.ro</em> mutató</a></li>\n    <li><a href=\"https://covidtracker.bsg.ox.ac.uk/\" target=\"_blank\">Oxford <em>Government Response Tracker</em></a></li>\n    <li><a href=\"https://www.reuters.com/\" target=\"_blank\"><em>Hírek</em> - Reuters</a>, <a href=\"https://bloomberg.com/\" target=\"_blank\">Bloomberg</a>, <a href=\"https://news.bbc.co.uk/\" target=\"_blank\">BBC</a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-coffee\"></i>&nbsp;&nbsp;Csapatunk</h4><div><ul class=\"credit\">\n    <li><b>B&aacute;lint Csaba&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/csaba-b%C3%A1lint-cfa-16b9a665/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Csala D&eacute;nes&nbsp;<a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/csaladenes/\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a><a title=\"Email\"\n                href=\"mailto:mail@csaladen.es\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa\n            fa-envelope\"></i></a></b></li>\n    <li><b>Cs&iacute;ki Ott&oacute;&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/ott%C3%B3-cs%C3%ADki-a01820109/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Nagy B&aacute;lint Zsolt&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/balint-zsolt-nagy-phd-8796621/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>R&aacute;cz B&eacute;la-Gergely&nbsp;<a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/raczbela/\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Sz&aacute;sz Levente <a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/leventeszasz/\" target=\"_blank\"\n                rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a><a title=\"Email\" href=\"mailto:levente.szasz@econ.ubbcluj.ro\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa\n            fa-envelope\"></i></a></b></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 65 },
   "content": "<p><h4><i class=\"fa fa-trophy\"></i>&nbsp;&nbsp;Díjaink</h4><div><ul class=\"other\">\n    <li><a href=\"https://cgdv.github.io/challenges/COVID-19/results1.html\" target=\"_blank\">Flattening the curve<i> - COVID-19 Data Challenge</i></a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "content": "<div style=\"width:100%;border-bottom:1px solid lightGray;padding-top:0px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "innius-video-panel",
   "gridPos": { "h": 4, "w": 7, "x": 1, "y": 72 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "innius-video-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 72 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 72 },
   "content": "<p><h4><i class=\"fa fa-pencil\"></i>&nbsp;&nbsp;Hivatkozás</h4><div>BBTE-KGTK (2020): COVID-19 - Romanian Economic Impact Monitor, https://econ.ubbcluj.ro/coronavirus/, utolsó betöltés dátuma:\n 2021.03.29</div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "content": "<div style=\"width:100%;border-bottom:1px solid lightGray;padding-top:0px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 1, "y": 77 },
   "content": "<a target=\"_blank\" href=\"https://www.ubbcluj.ro/hu/\"><img id=\"logo\" class=\"logo\" alt=\"Babeș-Bolyai Tudományegyetem\" src=\"//covid-large-html.csaladen.es/img/logo_UBB_hu.png\" style=\"height:70px!important;width:200px!important;\"/></a>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 77 },
   "content": "<br><div class=\"lang\" style=\"text-align:left;\">Copyright &copy; 2021 | <a target=\"_blank\" href=\"https://www.ubbcluj.ro/hu/\">Babeș-Bolyai Tudományegyetem</a> | <a target=\"_blank\" href=\"https://econ.ubbcluj.ro/\">FSEGA</a></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 77 },
   "content": "<br><div class=\"lang\" style=\"text-align:left;\">A vizualizációkat <a target=\"_blank\" href=\"http://grafana.org/\"><img src=\"https://grafana.com/favicon.ico\" style=\"height:20px;width:20px;margin-bottom:0px;\">&nbsp;Grafana</a>-ban készítette <a target=\"_blank\" href=\"https://www.csaladen.es/\"><img src=\"https://www.csaladen.es/favicon.ico\" style=\"height:20px;width:20px;margin-bottom:-1px;\">&nbsp;Csala Dénes</a></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
   "content": "<div style=\"width:100%;padding-top:20px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  }
 ]
}