{
 "title": "Română",
 "time": { "from": "now-384d", "to": "now+14d" },
 "templating": {
  "list": [
   { "name": "lang", "query": "HU,RO,EN" },
   { "name": "theme", "query": "dark,light" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "content": "<a target=\"_blank\" href=\"https://econ.ubbcluj.ro/\"><img id=\"flogo\" class=\"flogo\" alt=\"Universitatea Babeș-Bolyai\" src=\"//covid-large-html.csaladen.es/img/fsega_ro.png\" style=\"height:80px!important;width:330px!important;\"/></a>"
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 1, "x": 7, "y": 0 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 0 },
   "content": "<div style=\"text-align:left;\"><h1>COVID-19 – Romanian Economic Impact Monitor</h1><h3> Impactul pandemiei de coronavirus asupra economiei din România: date, analize și previziuni</h3></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "content": "<br><div class=\"lang\" style=\"text-align: center; font-size:16px;\">&nbsp;&nbsp;<a target=\"_self\" title=\"Română\" href=\"/d/ro\">RO</a>&nbsp;&nbsp;<a target=\"_self\" title=\"Magyar\" href=\"/d/hu\">HU</a>&nbsp;&nbsp;<a target=\"_self\" title=\"English\" href=\"/d/en\">EN</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"fa fa-paint-brush\"></i>&nbsp;&nbsp;<a target=\"_self\" title=\"Temă închisă\" href=\"/d/ro\"><i class=\"fa fa-circle\"></i></a>&nbsp;&nbsp;<a target=\"_self\" title=\"Temă deschisă\" href=\"/d/ro-light?theme=light\"><i class=\"fa fa-circle-o\"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style=\"font-size:20px;\" target=\"_blank\" title=\"Facebook\" href=\"https://www.facebook.com/covid19.roeim\"><i class=\"fa fa-facebook\"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style=\"font-size:20px;\" target=\"_blank\" title=\"Help\" href=\"https://github.com/denesdata/covid19-romania/wiki\"><i class=\"fa fa-question\"></i></a></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    },
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 5 },
   "content": "<p><span style=\"font-size:18px;\">Au trecut <span style=\"font-size:26px;color:#F2CC0C;\"><b>433</b></span> zile de la primul caz de coronavirus din România și în prezent sunt <span style=\"font-size:26px;color:#ff780a;\"><b>27&nbsp;265</b></span> cazuri active.</span></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Rata de incidență pe localități 📆 3 mai 2021",
   "type": "innius-video-panel",
   "description": "🕑 Actualizat la ora 10:34 în data de 3 mai 2021  \n  \nRata de incidență (totalul cazurilor noi din ultimele două săptămâni/1000 de locuitori - de la 17 până 3 zile înainte de data afișată) pe localități (unități administrative teritoriale - UAT).   \n  \n📊 [data.gov.ro](https://data.gov.ro/dataset/transparenta-covid)",
   "gridPos": { "h": 13, "w": 1, "x": 7, "y": 5 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Cazuri confirmate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vindecări",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "heals" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Decese",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Persoane imunizate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "total_immunized" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vaccine1",
     "query": "SELECT mean(\"value\") FROM \"base\".\"vaccine1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'total_immunized' OR \"type\" = 'total_first')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "total_immunized" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "total_first" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 9 },
   "content": "Proiect de cercetare care include și realizarea acestei platforme online specializate, prin care cercetătorii universității implicați în acest demers științific publică o serie de date relevante privind impactul economic al pandemiei COVID-19 în forma unor infografice interactive, menite să arate o imagine comprehensivă, actualizată în timp real a situației economiei românești. Obiectivul principal al proiectului constă în oferirea unui sprijin real factorilor decizionali din politica și economia românească prin realizarea și actualizarea frecventă a analizei situației generate de epidemia de COVID-19, respectiv prin oferirea unui punct de pornire pentru realizarea unor scenarii de previziune pentru o mai bună protejare a societății, a companiilor, a angajaților acestora, respectiv a lanțurilor de aprovizionare din economia reală.",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Previziune PIB anual (2021)",
   "type": "singlestat",
   "description": "Prognoză anuală. Scenariu de bază.  \n📊 Calcule proprii",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "gdp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Previziune PIB trimestrial (Q1 2021 vs. Q4 2020)",
   "type": "singlestat",
   "description": "Prognoză trimestrială. Scenariu de bază.  \n📊 Calcule proprii",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "gdpq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deprecierea leului față de euro",
   "type": "singlestat",
   "description": "Deprecierea leului față de euro de la raportarea primului caz de Covid-19 în România (📅 26 februarie).  \n📊 Calcule proprii bazate pe date de la [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "xch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evoluția indicelui BET",
   "type": "singlestat",
   "description": "Evoluția indicelui BET de la raportarea primului caz de Covid-19 în România (📅 26 februarie).  \n📊 Calcule proprii bazate pe date de la [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "bet" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Previziune deficit bugetar anual (2021)",
   "type": "singlestat",
   "description": "  \n📊 [Consiliului Fiscal al României](http://www.consiliulfiscal.ro/Opinie%20CF%20buget%202021%20si%20SFB.pdf)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "status_plot14" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evoluția numărului angajaților",
   "type": "singlestat",
   "description": "Comparativ cu media anului 2019 (=100), ajustat sezonier  \n📊 [INS](https://insse.ro/cms/ro)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "employees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Șomaj",
   "type": "singlestat",
   "description": "  \n📊 [INS](https://insse.ro/cms/ro)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "unemployment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indice de mobilitate Google",
   "type": "singlestat",
   "description": "Indice compozit de mobilitate, calculat pe baza datelor de la Google. Arată mobilitatea medie relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie. Valori rezidențiale inversate.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance3",
     "select": [
      [
       { "params": [ "mobility_mini" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "content": "<div style=\"text-align:right;\"><i class=\"fa fa-clock-o\"></i>&nbsp;Actualizarea datelor se realizează zilnic la ora <b>14:00</b>. Ultima actualizare: <b>03/05/2021</b></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  { "title": "Situația actuală", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Rata de incidență pe localități 📆 3 mai 2021",
   "type": "innius-video-panel",
   "description": "🕑 Actualizat la ora 10:34 în data de 3 mai 2021  \n  \nRata de incidență (totalul cazurilor noi din ultimele două săptămâni/1000 de locuitori - de la 17 până 3 zile înainte de data afișată) pe localități (unități administrative teritoriale - UAT).   \n  \n📊 [data.gov.ro](https://data.gov.ro/dataset/transparenta-covid)",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "title": "Persoane care au primit prima doză de vaccin (+) si numărul persoanelor imunizate (-)",
   "type": "graph",
   "description": "Persoane care au primit prima doză de vaccin (axa pozitivă) si numărul persoanelor imunizate pe tipuri de vaccin (axa negativă)  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vaccine1",
     "query": "SELECT mean(\"value\") FROM \"base\".\"vaccine1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'total_administered' OR \"type\" = 'total_administered_astra_zeneca' OR \"type\" = 'total_administered_pfizer' OR \"type\" = 'total_administered_moderna')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered" },
      {
       "condition": "AND",
       "key": "type",
       "operator": "!=",
       "value": "total_administered_astra_zeneca"
      },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered_moderna" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "total_administered_pfizer" }
     ]
    }
   ]
  },
  {
   "title": "Previziune pe termen scurt a cazurilor noi zilnice",
   "type": "graph",
   "description": "  \n📊 Estimare proprie, actualizat săptămânal",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
     ]
    }
   ]
  },
  {
   "title": "Evoluția ratei de incidență pe județe (totalul cazurilor noi din ultimele două săptămâni/1000 de locuitori)",
   "type": "heatmap",
   "description": "Evoluția ratei de incidență pe județe (totalul cazurilor noi din ultimele două săptămâni/1000 de locuitori)  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/), Estimare proprie",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "alias": "$tag_county",
     "groupBy": [
      { "params": [ "county" ], "type": "tag" }
     ],
     "measurement": "counties3",
     "select": [
      [
       { "params": [ "case_14_cap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
     ]
    }
   ]
  },
  {
   "title": "Evoluția cazurilor, vindecărilor și a deceselor în total",
   "type": "graph",
   "description": "Toate datele provin de la sursele oficiale guvernamentale. Cazurile active sunt o metrică calculată. <b>Cazuri active (estimare proprie)</b> reprezintă suma cumulativă a cazurilor noi din ultimele 14 zile. <b>Cazuri active (oficial)</b> este suma Deceselor și Vindecărilor scăzute din Totalul Cazurilor.  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/)",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance1",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
     ]
    }
   ]
  },
  {
   "title": "Evoluția cazurilor, vindecărilor și a deceselor pe zi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "case/test" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "death_rate" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"governance\".\"governance1\" WHERE $timeFilter GROUP BY time(1d), \"/^$lang$/\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "case/test" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "death_rate" }
     ]
    }
   ]
  },
  {
   "title": "Rata testelor pozitive și rata de mortalitate",
   "type": "graph",
   "description": "Rata testelor pozitive este numărul de cazuri noi împărțit la numărul de teste zilnice. Rata mortalității este numărul de decese noi zilnice împărțit la numărul de cazuri noi.  \n📊 [Știri Oficiale - COVID-19](https://stirioficiale.ro/), [Universitatea Johns Hopkins - CSSE](https://coronavirus.jhu.edu/data/mortality)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_langtype",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "langtype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT mean(\"value\") FROM \"base\".\"governance2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'case/test' OR \"type\" = 'death_rate')) AND $timeFilter GROUP BY time(1d), \"langtype\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "case/test" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "death_rate" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "governance2",
     "query": "SELECT moving_average(mean(\"value\"), 14) FROM \"base\".\"governance2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"type\" = 'death_rate' OR \"type\" = 'case/test')) AND $timeFilter GROUP BY time(1d), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "14" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "death_rate" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "case/test" }
     ]
    }
   ]
  },
  {
   "title": "Știri",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 },
     "content": "<p><h2><i class=\"fa fa-newspaper-o\"></i>&nbsp;&nbsp;Știri</h2><div>Actualități din partea echipei de proiect, apariții în mass-media, știri și anunțuri oficiale guvernamentale</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Postările noastre pe Facebook",
     "type": "innius-video-panel",
     "description": "  \n📊 [Pagină Oficială Facebook COVID-19 Romanian Economic Impact Monitor](https://www.facebook.com/covid19.roeim)",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 51 },
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "counties2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Apariții în mass-media",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 51 },
     "targets": [
      {
       "measurement": "global2",
       "query": "SELECT  \"media\", \"desc\", \"lang\",\"type\", \"link\" FROM \"base\".\"news1\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Evenimente globale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
     "content": "<p><h2><i class=\"fa fa-globe\"></i>&nbsp;&nbsp;Evenimente globale</h2><div>Cele mai importante evenimente și măsuri economico-sociale la scară globală</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evoluția cazurilor active în lume",
     "type": "graph",
     "description": "❗ 📈 scală logaritmică  \n📊 [Universitatea Johns Hopkins - CSSE](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "global3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      },
      {
       "alias": "România (oficial)",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "active" }
       ]
      },
      {
       "alias": "România (estimare proprie)",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
       ]
      }
     ]
    },
    {
     "title": "Evenimente globale",
     "type": "table-old",
     "description": "Cele mai importante evenimente și măsuri economico-sociale la scară globală  \n📊 [Reuters](https://www.reuters.com/), [Bloomberg](https://bloomberg.com/), [BBC](https://news.bbc.co.uk/), [WHO](https://www.who.int/), [BCE](https://www.ecb.europa.eu/), [FMI](https://www.imf.org/external/index.htm), [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "measurement": "global2",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Măsuri guvernamentale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 63 },
     "content": "<p><h2><i class=\"fa fa-gavel\"></i>&nbsp;&nbsp;Măsuri guvernamentale</h2><div>Rezumatul măsurilor sociale și economice guvernamentale</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Severitatea măsurilor guvernamentale în România și în alte țări",
     "type": "graph",
     "description": "Severitatea este un indicator relativ în intervalul 0 (ușor) - 100 (sever).  \n📊 [Universitatea din Oxford - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langcountry",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langcountry" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "severity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "lang2", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "stringency" }
       ]
      }
     ]
    },
    {
     "title": "Răspunsul populației la severitatea măsurilor guvernamentale",
     "type": "innius-video-panel",
     "description": "Severitatea este un indicator relativ în intervalul 0 (ușor) - 100 (sever).  \n📊 [Universitatea din Oxford - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 66 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evoluția severității măsurilor guvernamentale și scăderea mobilității lângă cazurile noi zilnice",
     "type": "graph",
     "description": "Mobilitatea și severitatea sunt indicatori relativi măsurați pe o scară de 0-100. Valorile mobilității sunt valori inverse.  \n📊 [Universitatea din Oxford - COVID-19 Government Response Tracker](https://covidtracker.bsg.ox.ac.uk/)",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "severity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "lang2", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "country", "operator": "=", "value": "ro" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "stringency" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case" }
       ]
      },
      {
       "alias": "Scăderea mobilității",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance3",
       "select": [
        [
         { "params": [ "mobility_mini" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Măsuri economice",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Lista măsurilor economice",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 77 },
     "targets": [
      {
       "measurement": "social1",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social1\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "desc2" ], "type": "field" }
        ],
        [
         { "params": [ "desc3" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Măsuri sociale",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Lista măsurilor sociale",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 84 },
     "targets": [
      {
       "measurement": "social2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social2\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Măsuri financiare",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Lista măsurilor financiare",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 91 },
     "targets": [
      {
       "measurement": "global2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "desc" ], "type": "field" }
        ],
        [
         { "params": [ "country" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Indicatori macroeconomici",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 },
     "content": "<p><h2><i class=\"fa fa-forward\"></i>&nbsp;&nbsp;Indicatori macroeconomici</h2><div>Prezentarea indicatorilor macroeconomici cheie</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Creșterea anuală a PIB vs. estimările de piață și de model (DFM)",
     "type": "innius-video-panel",
     "description": "Am estimat un model cu factori dinamici (DFM) pentru a oferi, în timp real, prognoze de creștere economică pe termen scurt. DFM-urile sunt utilizate pentru a exploata informații utile dintr-o gamă largă de indicatori cu frecvență ridicată. Modelul nostru include serii lunare de date care acoperă diferite sectoare economice (servicii de piață, industrie, construcții), precum și indicatori ai sentimentului economic, prețului și pieței forței de muncă. Pe măsură ce mai multe informații devin disponibile, este de așteptat ca estimările de creștere a PIB-ului furnizate de DFM vor fi mai precise. Valorile prezentate reprezintă media mobilă de trei luni a ratei de creștere anuală.  \n📊 [INS](https://insse.ro/cms/ro), [Reuters](https://www.reuters.com/), calcule proprii",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Harta \"termică\" a economiei",
     "type": "innius-video-panel",
     "description": "Harta \"termică\" adună și prezintă evoluția mai multor indicatori macroeconomici cheie în ultima perioadă  \n🟥 mai rău ◄ medie 2015-2019 ► mai bun 🟦",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 54 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Creșterea anuală a PIB vs. estimările de piață și ale modelului (DFM) cu intervale de incertitudine",
     "type": "graph",
     "description": "Am estimat un model cu factori dinamici (DFM) pentru a oferi, în timp real, prognoze de creștere economică pe termen scurt. DFM-urile sunt utilizate pentru a exploata informații utile dintr-o gamă largă de indicatori cu frecvență ridicată. Modelul nostru include serii lunare de date care acoperă diferite sectoare economice (servicii de piață, industrie, construcții), precum și indicatori ai sentimentului economic, prețului și pieței forței de muncă. Pe măsură ce mai multe informații devin disponibile, este de așteptat ca estimările de creștere a PIB-ului furnizate de DFM vor fi mai precise. Valorile prezentate reprezintă media mobilă de trei luni a ratei de creștere anuală.  \n📊 [INS](https://insse.ro/cms/ro), [Reuters](https://www.reuters.com/), calcule proprii",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "macro",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "Range68" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Reacții ale piețelor financiare",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
     "content": "<p><h2><i class=\"fa fa-line-chart\"></i>&nbsp;&nbsp;Reacții ale piețelor financiare</h2><div>Valorile celor mai importanți indici bursieri de pe piețele dezvoltate și regionale, rentabilități și volatilitate. Valorile corespunzătoare din perioada critică a crizei din 2008, pentru comparație (începând de la 📆 2008-09-16, respectiv 2020-02-26 📆).</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Cazuri COVID19 active",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "BET închidere",
     "type": "graph",
     "description": "Prețul de închidere al indicelui bursier BET (București)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "BET" }
       ]
      }
     ]
    },
    {
     "title": "FTSE100 închidere",
     "type": "graph",
     "description": "Prețul de închidere al indicelui bursier FTSE 100 (Londra)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "FTSE 100" }
       ]
      }
     ]
    },
    {
     "title": "SP500 închidere",
     "type": "graph",
     "description": "Prețul de închidere al indicelui bursier SP500 (New York)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "S&P 500" }
       ]
      }
     ]
    },
    {
     "title": "Stoxx600 închidere",
     "type": "graph",
     "description": "Prețul de închidere al indicelui bursier transeuropean Stoxx 600  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX" }
       ]
      }
     ]
    },
    {
     "title": "DAX închidere",
     "type": "graph",
     "description": "Prețul de închidere al indicelui bursier DAX (Frankfurt)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX" }
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "global3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "ww" }
       ]
      },
      {
       "alias": "România",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "case14" }
       ]
      }
     ]
    },
    {
     "title": "BET volatilitate",
     "type": "graph",
     "description": "Volatilitatea (abaterea medie pătratică) zilnică a indicelui bursier BET (București)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "BET volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "FTSE100 volatilitate",
     "type": "graph",
     "description": "Volatilitatea (abaterea medie pătratică) zilnică a indicelui bursier FTSE 100 (Londra)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "FTSE 100 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "SP500 volatilitate",
     "type": "graph",
     "description": "Volatilitatea (abaterea medie pătratică) zilnică a indicelui bursier SP500 (New York)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "SP500 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "Stoxx600 volatilitate",
     "type": "graph",
     "description": "Volatilitatea (abaterea medie pătratică) zilnică a indicelui bursier transeuropean Stoxx 600  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Stoxx 600 volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "DAX volatilitate",
     "type": "graph",
     "description": "Volatilitatea (abaterea medie pătratică) zilnică a indicelui bursier DAX (Frankfurt)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "year" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Bid/ask 10 ev (%)' OR \"stock\" = 'Bid/ask 5 ev (%)' OR \"stock\" = 'Bid/ask 3 ev (%)' OR \"stock\" = 'Bid/ask 12 honap (%)' OR \"stock\" = 'Bid/ask 6 honap (%)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "DAX volatilitas" }
       ]
      }
     ]
    },
    {
     "title": "Cursuri de schimb RON",
     "type": "graph",
     "description": "Evoluția cursului de schimb valutar al leului românesc față de euro și de dolarul american, începând de la data primei infecții cu noul coronavirus.  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks2",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks2\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'EUR - RON (valutaárfolyam)' OR \"stock\" = 'USD - RON (valutaárfolyam)')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "EUR - RON (valutaárfolyam)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "USD - RON (valutaárfolyam)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "EUR - PLN (valutaárfolyam)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "EUR - HUF (valutaárfolyam)" }
       ]
      }
     ]
    },
    {
     "title": "Spreadurile instrumentelor de trezorerie române",
     "type": "graph",
     "description": "Diferența dintre randamentele de cumpărare și vânzare ale bonurilor de trezorerie române de 6 luni și un an, respectiv a obligațiunilor de stat române de 3 ani, 5 ani și 10 ani    \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/  AND \"year\" = '2020' AND (\"stock\" = 'Bid/ask 5 ev' OR \"stock\" = 'Bid/ask 12 honap ' OR \"stock\" = 'Bid/ask 6 honap')) AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 10 ev (%)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "Bid/ask 5 ev (%)" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "Bid/ask 3 ev (%)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 12 honap (%)" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Bid/ask 6 honap (%)" }
       ]
      }
     ]
    },
    {
     "title": "Prețul petrolului",
     "type": "graph",
     "description": "Prețul la termen al petrolului Brent (Marea Nordică) și al petrolului WTI (West Texas Intermediate)  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND (\"stock\" = 'Brent' OR \"stock\" = 'WTI') AND \"year\" = '2020') AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "Brent" },
        { "condition": "OR", "key": "stock", "operator": "=", "value": "WTI" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      }
     ]
    },
    {
     "title": "Rata dobânzii de pe piața interbancară din România",
     "type": "graph",
     "description": "Rata dobânzii de pe piața interbancară din România la 3 luni  \n📊 [Thomson Reuters Eikon](https://eikon.thomsonreuters.com/index.html)",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langstock",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langstock" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "stocks1",
       "query": "SELECT mean(\"value\") FROM \"base\".\"stocks1\" WHERE (\"lang\" =~ /^$lang$/ AND \"stock\" = 'ROBOR3M') AND $timeFilter GROUP BY time(1d), \"langstock\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "stock", "operator": "=", "value": "ROBOR3M" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "governance2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "cases" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Măsuri ale companiilor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
     "content": "<p><h2><i class=\"fa fa-car\"></i>&nbsp;&nbsp;Măsuri ale companiilor</h2><div>Reacțiile companiilor din top 50 din România la pandemia de coronavirus</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Cele mai mari 50 de firme după cifra de afaceri (2018, RON)",
     "type": "savantly-heatmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "format": "none",
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firms1",
       "select": [
        [
         { "params": [ "revenue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cele mai mari 50 de firme după număr de angajați (2018)",
     "type": "savantly-heatmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "format": "none",
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "firms1",
       "select": [
        [
         { "params": [ "employees" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Măsuri ale firmelor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Lista măsurilor firmelor",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 15, "x": 9, "y": 65 },
     "targets": [
      {
       "measurement": "firms2",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "name" ], "type": "field" }
        ],
        [
         { "params": [ "event" ], "type": "field" }
        ],
        [
         { "params": [ "type" ], "type": "field" }
        ],
        [
         { "params": [ "link" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Activitatea pe Facebook a firmelor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "panelId": 135 }
     ]
    },
    {
     "title": "Reacții ale firmelor",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 16, "x": 0, "y": 79 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "firms3",
       "query": "SELECT \"desc\", \"desc2\", \"desc3\", \"link\" FROM \"base\".\"social3\" WHERE (\"lang\" =~ /^$lang$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "revenue" ], "type": "field" }
        ],
        [
         { "params": [ "sulyos" ], "type": "field" }
        ],
        [
         { "params": [ "teljes_leallas" ], "type": "field" }
        ],
        [
         { "params": [ "reszleges_leallas" ], "type": "field" }
        ],
        [
         { "params": [ "szemelyzet_csok" ], "type": "field" }
        ],
        [
         { "params": [ "home_office" ], "type": "field" }
        ],
        [
         { "params": [ "higenia" ], "type": "field" }
        ],
        [
         { "params": [ "testho" ], "type": "field" }
        ],
        [
         { "params": [ "tamogatas" ], "type": "field" }
        ],
        [
         { "params": [ "uzleti_utak" ], "type": "field" }
        ],
        [
         { "params": [ "adomany" ], "type": "field" }
        ],
        [
         { "params": [ "informalas" ], "type": "field" }
        ],
        [
         { "params": [ "egyebi" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 79 },
     "content": "<table class=\"legend\"><tr><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td> ⛔</td><td>Severitate</td></tr><tr><td>🔴</td><td>Oprire totală</td></tr><tr><td>⭕</td><td>Oprire parțială</td></tr><tr><td>😐</td><td>Scăderea numărului angajaților (inclusiv prin șomaj tehnic)</td></tr><tr><td>🏠</td><td>Muncă de la domiciliu, program flexibil</td></tr><tr><td> 💧</td><td>Măsuri de igienă și distanțare</td></tr><tr><td>🌡</td><td>Măsurarea temperaturii</td></tr><tr><td>💲</td><td>Sprijinirea angajaților (linie telefonică etc.)</td></tr><tr><td>✈</td><td>Anularea sau limitarea deplasărilor profesionale</td></tr><tr><td>🎈</td><td>Donație</td></tr><tr><td>ℹ</td><td>Informare</td></tr><tr><td>✖</td><td>Altele</td></tr>",
     "targets": [
      { "panelId": 90 }
     ]
    }
   ]
  },
  {
   "title": "Efecte sectoriale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "content": "<p><h2><i class=\"fa fa-industry\"></i>&nbsp;&nbsp;Efecte sectoriale</h2><div>Previziuni privind impactul pandemiei coronavirus asupra principalelor sectoare din România</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Sectoarele cele mai afectate după dimensiune și evoluție PIB",
     "type": "innius-video-panel",
     "description": "Previziune bazată pe agregarea estimărilor privind evoluția PIB din subsectoarele componente  \n📊 Calcule proprii",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Previziune PIB trimestrial (Q1 2021 vs. Q4 2020)",
     "type": "innius-video-panel",
     "description": "Prognoză trimestrială. Scenariu de bază.  \n📊 Calcule proprii",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
     "targets": [
      { "panelId": 90 }
     ]
    }
   ]
  },
  {
   "title": "Indici de mobilitate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 55 },
     "content": "<p><h2><i class=\"fa fa-train\"></i>&nbsp;&nbsp;Indici de mobilitate</h2><div>Efectele pandemiei asupra mobilității în mai multe dimensiuni (loc de muncă, acasă, transport comun, cumpărături, timp liber) pe județe. Din cauza schmibării metodologiei anunțat de Google, datele nu sunt complete între 📅 17.08.2020 și 📅 11.09.2020.</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evoluția mobilității la nivel național",
     "type": "innius-video-panel",
     "description": "Indice compozit de mobilitate, calculat pe baza datelor de la Google. Indicele arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie. Data poate fi schimbată utilizând axa de dedesubt (medii săptămânale calculate până la datele afișate). Valori rezidențiale inversate.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 58 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evoluția mobilității pe județe",
     "type": "graph",
     "description": "Indice compozit de mobilitate, calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie. Valori rezidențiale inversate.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility4",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Evoluția mobilității pe domenii",
     "type": "graph",
     "description": "Componentele indicelui de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie 2020 și evoluția trecerilor de frontieră față de aceeași zi a anului 2019.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro), [Poliția de Frontieră](https://www.politiadefrontiera.ro/ro/main/n-date-deschise-17/?fy=2019&page_no=1&fm=4)",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langindicator",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langindicator" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      },
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility3",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "border_change" }
       ]
      }
     ]
    },
    {
     "title": "Clădiri rezidențiale",
     "type": "graph",
     "description": "Indice de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie, în domeniul respectiv, normalizat pentru fiecare zi de săptămână.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "residential_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Locuri de muncă",
     "type": "graph",
     "description": "Indice de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie, în domeniul respectiv.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "workplaces_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Stații de transport public",
     "type": "graph",
     "description": "Indice de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie, în domeniul respectiv.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "transit_stations_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Magazine alimentare și farmacii",
     "type": "graph",
     "description": "Indice de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie, în domeniul respectiv.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "grocery_and_pharmacy_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Vânzare cu amănuntul și recreere",
     "type": "graph",
     "description": "Indice de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie, în domeniul respectiv.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "retail_and_recreation_percent_change_from_baseline"
        }
       ]
      }
     ]
    },
    {
     "title": "Parcuri",
     "type": "graph",
     "description": "Indice de mobilitate calculat pe baza datelor de la Google. Arată mobilitatea relativă a populației comparativ cu media perioadei 📅 15 februarie - 1 martie, în domeniul respectiv.  \n📊 Calcule proprii bazate pe date de la [Google](https://www.google.com/covid19/mobility/?hl=ro)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mobility",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        {
         "condition": "AND",
         "key": "indicator",
         "operator": "=",
         "value": "parks_percent_change_from_baseline"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Piața imobiliară",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
     "content": "<p><h2><i class=\"fa fa-home\"></i>&nbsp;&nbsp;Piața imobiliară</h2><div>Prețul mediu și numărul tranzacțiilor imobiliare pentru orașe mari și la nivel național și județean. Valorile corespunzătoare din perioada critică a crizei din 2008, pentru comparație (începând de la 📆 decembrie 2019, respectiv 📆 iunie 2008).</div></p>",
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Prețuri medii ale apartamentelor (€/m²) în orașele mari din țară",
     "type": "innius-video-panel",
     "description": "Prețul mediu în euro pe metru pătrat, defalcat pe județe  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 59 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Prețuri medii ale apartamentelor (€/m²) în 2020",
     "type": "graph",
     "description": "Prețul mediu în euro pe metru pătrat, defalcat pe județe, din ianuarie 2020  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "currencyEUR" }
     ],
     "targets": [
      {
       "alias": "$tag_city",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "city" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare3",
       "select": [
        [
         { "params": [ "price" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
       ]
      }
     ]
    },
    {
     "title": "Prețuri medii ale apartamentelor în (€/m²) 2008",
     "type": "graph",
     "description": "Prețul mediu în euro pe metru pătrat, defalcat pe județe, din septembrie 2008 pentru comparație  \n📊 [Imobiliare.ro](www.imobiliare.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "currencyEUR" }
     ],
     "targets": [
      {
       "alias": "$tag_city",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "city" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare3",
       "select": [
        [
         { "params": [ "price" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" },
        { "condition": "AND", "key": "year", "operator": "=", "value": "2008" }
       ]
      }
     ]
    },
    {
     "title": "Evoluția lunară a numărului de tranzacții imobiliare la nivel național",
     "type": "innius-video-panel",
     "description": "Evoluția numărului de tranzacții imobiliare (de vânzare-cumpărare) la nivel național și județean comparat cu media perioadei 📅 decembrie 2019 - februarie 2020  \n📊 [Agenția Națională de Cadastru și Publicitate Imobiliară](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 71 },
     "targets": [
      { "panelId": 90 }
     ]
    },
    {
     "title": "Evoluția numărului de tranzacții imobiliare pe județe",
     "type": "graph",
     "description": "Evoluția numărului de tranzacții imobiliare (de vânzare-cumpărare) la nivel național și județean comparat cu media perioadei 📅 decembrie 2019 - februarie 2020  \n📊 [Agenția Națională de Cadastru și Publicitate Imobiliară](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    },
    {
     "title": "Numărul de tranzacții imobiliare pe județe",
     "type": "graph",
     "description": "Numărul tranzacțiilor imobiliare la nivel național și județean❗ 📈 scară logaritmică  \n📊 [Agenția Națională de Cadastru și Publicitate Imobiliară](www.ancpi.ro)",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_langtype",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "langtype" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "imobiliare1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "lang", "operator": "=~", "value": "/^$lang$/" }
       ]
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "content": "<div style=\"width:100%;border-bottom:1px solid lightGray;padding-top:40px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 1, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-ellipsis-h\"></i>&nbsp;&nbsp;Alte pagini utile</h4><div><ul class=\"other\">\n    <li><a href=\"https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6\" target=\"_blank\">Johns Hopkins - <em>CSSE</em></a></li>\n    <li><a href=\"https://www.worldometers.info/coronavirus/\" target=\"_blank\">Worldometers - <em>Coronavirus</em></a></li>\n    <li><a href=\"https://datelazi.ro/\" target=\"_blank\">Date la Zi - <em>COVID-19</em></a></li>\n    <li><a href=\"https://stirioficiale.ro/\" target=\"_blank\">Știri Oficiale - <em>COVID-19</em></a></li>\n    <li><a href=\"https://instnsp.maps.arcgis.com/apps/opsdashboard/index.html#/5eced796595b4ee585bcdba03e30c127\">INSP - <em>Harta Coronavirus</em></a></li>\n    <li><a href=\"https://coronavirus-esriro.hub.arcgis.com/\" target=\"_blank\">ESRI Romania - <em>COVID19 Hub</em></a></li>\n    <li><a href=\"https://coronavirus.casajurnalistului.ro/\" target=\"_blank\">Casa Jurnalistului - <em>Monitorizare Coronavirus</em></a></li>\n    <li><a href=\"https://www.hartacoronavirus.ro/\" target=\"_blank\">HartaCoronavirus.ro</a></li>\n    <li><a href=\"https://covid.solidaritatea-sanitara.ro/\" target=\"_blank\">Solidaritate Sanitara - <em>Salariați din sănătate infectați</em></a></li>\n    <li><a href=\"https://www.graphs.ro/resources.php\" target=\"_blank\">Graphs.ro - <em>JSON Data</em></a></li>\n    <li><a href=\"https://atlo.team/koronamonitor/\" target=\"_blank\">ATLO - <em>Koronamonitor</em></a></li>\n    <li><a href=\"http://statisztikak.erdelystat.ro/vizualizaciok/erdelyi-koronamonitor/2\" target=\"_blank\">Erd&eacute;lystat - <em>Koronamonitor</em></a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-database\"></i>&nbsp;&nbsp;Sursele datelor</h4><div><ul class=\"other\">\n    <li><a href=\"https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series\" target=\"_blank\">Universitatea Johns Hopkins - <em>CSSE</em></a></li>\n    <li><a href=\"https://stirioficiale.ro/\" target=\"_blank\">Știri Oficiale - <em>COVID-19</em></a></li>\n    <li><a href=\"https://www.who.int/\" target=\"_blank\">Organizația Mondială a Sănătății</a></li>\n    <li><a href=\"https://insse.ro/cms/ro\" target=\"_blank\">Institutul Național de Statistică</a></li>\n    <li><a href=\"https://www.mfinante.gov.ro/\" target=\"_blank\">Ministerul Finanțelor Publice</a></li>\n    <li><a href=\"http://mmuncii.ro/j33/index.php/ro/\" target=\"_blank\">Ministerul Muncii și Protecției Sociale</a></li>\n    <li><a href=\"http://www.consiliulfiscal.ro/Opinie%20Rectificare%20I%202020.pdf\" target=\"_blank\">Consiliului Fiscal al României</a></li>\n    <li><a href=\"https://www.bnr.ro/Home.aspx\" target=\"_blank\">Banca Națională a României</a></li>\n    <li><a href=\"https://ec.europa.eu/info/business-economy-euro/indicators-statistics/economic-databases/business-and-consumer-surveys_en\" target=\"_blank\">Comisia Europeană</li>\n    <li><a href=\"https://www.ecb.europa.eu/\" target=\"_blank\">Banca Centrală Europeană</li>\n    <li><a href=\"https://www.imf.org/external/index.htm\" target=\"_blank\">Fondul Monetar Internațional</li><li><a href=\"https://eikon.thomsonreuters.com/index.html\" target=\"_blank\">Thomson Reuters - <em>Eikon</em></a></li>\n    <li><a href=\"https://www.google.com/covid19/mobility/\" target=\"_blank\">Google - <em>COVID-19 Mobilitate</em></a></li>\n    <li><a href=\"https://www.ancpi.ro/\" target=\"_blank\">Ag. Naț. de Cadastru și Publicitate Imobiliară</a></li>\n    <li><a href=\"https://www.imobiliare.ro/\" target=\"_blank\">Indicele - <em>Imobiliare.ro</em></a></li>\n    <li><a href=\"https://covidtracker.bsg.ox.ac.uk/\" target=\"_blank\">Oxford <em>Government Response Tracker</em></a></li>\n    <li><a href=\"https://www.reuters.com/\" target=\"_blank\"><em>Știri</em> - Reuters</a>, <a href=\"https://bloomberg.com/\" target=\"_blank\">Bloomberg</a>, <a href=\"https://news.bbc.co.uk/\" target=\"_blank\">BBC</a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "content": "<p><h4><i class=\"fa fa-coffee\"></i>&nbsp;&nbsp;Echipa noastră</h4><div><ul class=\"credit\">\n    <li><b>B&aacute;lint Csaba&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/csaba-b%C3%A1lint-cfa-16b9a665/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Csala D&eacute;nes&nbsp;<a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/csaladenes/\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a><a title=\"Email\"\n                href=\"mailto:mail@csaladen.es\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa\n            fa-envelope\"></i></a></b></li>\n    <li><b>Cs&iacute;ki Ott&oacute;&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/ott%C3%B3-cs%C3%ADki-a01820109/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Nagy B&aacute;lint Zsolt&nbsp;<a title=\"LinkedIn\"\n                href=\"https://www.linkedin.com/in/balint-zsolt-nagy-phd-8796621/\" target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i\n                    class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>R&aacute;cz B&eacute;la-Gergely&nbsp;<a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/raczbela/\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a></b></li>\n    <li><b>Sz&aacute;sz Levente <a title=\"LinkedIn\" href=\"https://www.linkedin.com/in/leventeszasz/\" target=\"_blank\"\n                rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa fa-linkedin\"></i></a><a title=\"Email\" href=\"mailto:levente.szasz@econ.ubbcluj.ro\"\n                target=\"_blank\" rel=\"noopener\">&nbsp;&nbsp;&nbsp;<i class=\"fa\n            fa-envelope\"></i></a></b></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 65 },
   "content": "<p><h4><i class=\"fa fa-trophy\"></i>&nbsp;&nbsp;Premiile noastre</h4><div><ul class=\"other\">\n    <li><a href=\"https://cgdv.github.io/challenges/COVID-19/results1.html\" target=\"_blank\">Flattening the curve<i> - COVID-19 Data Challenge</i></a></li>\n</ul></div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "content": "<div style=\"width:100%;border-bottom:1px solid lightGray;padding-top:0px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "innius-video-panel",
   "gridPos": { "h": 4, "w": 7, "x": 1, "y": 72 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "innius-video-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 72 },
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 72 },
   "content": "<p><h4><i class=\"fa fa-pencil\"></i>&nbsp;&nbsp;Referinţă</h4><div>UBB-FSEGA (2020): COVID-19 - Romanian Economic Impact Monitor, https://econ.ubbcluj.ro/coronavirus/, data ultimei accesări: 01/04/2021</div></p>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "content": "<div style=\"width:100%;border-bottom:1px solid lightGray;padding-top:0px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 1, "y": 77 },
   "content": "<a target=\"_blank\" href=\"https://www.ubbcluj.ro/ro/\"><img id=\"logo\" class=\"logo\" alt=\"Universitatea Babeș-Bolyai\" src=\"//covid-large-html.csaladen.es/img/logo_UBB_ro.png\" style=\"height:70px!important;width:200px!important;\"/></a>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 77 },
   "content": "<br><div class=\"lang\" style=\"text-align:left;\">Copyright &copy; 2021 | <a target=\"_blank\" href=\"https://www.ubbcluj.ro/ro/\">Universitatea Babeș-Bolyai</a> | <a target=\"_blank\" href=\"https://econ.ubbcluj.ro/\">FSEGA</a></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 77 },
   "content": "<br><div class=\"lang\" style=\"text-align:left;\">Vizualizările au fost create în <a target=\"_blank\" href=\"http://grafana.org/\"><img src=\"https://grafana.com/favicon.ico\" style=\"height:20px;width:20px;margin-bottom:0px;\">&nbsp;Grafana</a> de <a target=\"_blank\" href=\"https://www.csaladen.es/\"><img src=\"https://www.csaladen.es/favicon.ico\" style=\"height:20px;width:20px;margin-bottom:-1px;\">&nbsp;Dénes Csala</a></div>",
   "targets": [
    { "panelId": 90 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
   "content": "<div style=\"width:100%;padding-top:20px;\"></div>",
   "targets": [
    { "panelId": 90 }
   ]
  }
 ]
}